### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [cmda-bt/be-course-18-19#10]
# Package

## Name
Rowin

## Repo link
https://github.com/Rowin206/DatingApp

## Summary
I created a boilerplate for the dating app and researched/installed/tried the first npm packages that I definitely needed. I have also done a little bit of research on licensing, but I think, most of the time you'll end up with the MIT License. The easy thing is that Git itself has already created a [website](https://choosealicense.com/) with a kind of step-by-step plan where you can see which license is best for you.

## Resources used
https://www.npmjs.com/

## Any thoughts?

When I read the assignment for the first time, it was a little blurry. Immediately I had to look up what was meant by a boilerplate and did not know where to start.

Once we discussed it in the lesson and went through the steps, everything was immediately clear. I did not copy what they did in class, but I did remember it in parts. So that later on, at home, I could do it myself. I notice that it is easier to remember, when I do it by myself. But the hard thing is, not knowing where to start. 

Oh! And making things smaller and smaller to find the right NPM Package is sometimes hard as well.

**Comment by rijkvanzanten** [comment]
Hey Rowin! Good job.

* Consider adding `.DS_Store` to the `.gitignore` file so it doesn't sneak into the repo at a later moment
* You chose to list all the dependencies in the readme as well (nice!) but as you already ran into, it's a PITA to keep up to date (there is a dependency missing)

**Comment by dandevri** [comment]
Good job on investigating the difference license types.

> And making things smaller and smaller to find the right NPM Package is sometimes hard as well.

This is hard! Feel free to ask for feedback if your stuck.

**Comment by RowinVanAmsterdam** [comment]
> Hey Rowin! Good job.
> 
> * Consider adding `.DS_Store` to the `.gitignore` file so it doesn't sneak into the repo at a later moment
> * You chose to list all the dependencies in the readme as well (nice!) but as you already ran into, it's a PITA to keep up to date (there is a dependency missing)

Ah I see, you're right. I added '.DS_Store' and deleted the included packages in the Readme. I think especially that it is difficult to keep track of when you are going to work with a lot of packages, that is why I have taken it away.
