### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by woutarb** [cmda-bt/be-course-18-19#100]
# My Introduction

## Name
Wouter Bijnsdorp 

## Class
Tech 3

## About me
Metalhead, tabletoprpg, book, comic en videogame nerd.

## Goals
Opdoen van ervaring en kennis over nieuwe onderwerpen die ik nog niet ken

## Skill level
Beginner

## GitHub username
https://github.com/wouterBijns

## GitHub repository
https://github.com/wouterBijns/ProjectTechRepo

**Comment by dandevri** [comment]
👋 Hi Wouter, the link is added to the admin sheet.
