### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by robert-hoekstra** [cmda-bt/be-course-18-19#102]
# My Introduction

## Name
Robert Hoekstra

## Class
214 (Tech3)

## About me
26 year old barista went back to school to become a UX designer

## Goals
get to know the backend for prototyping.

## Skill level
Beginner

## GitHub username
https://github.com/robert-hoekstra

## GitHub repository
https://github.com/robert-hoekstra/BlokTech

Back-End repo solely for learning modules. Everything that should not be in the files of the dating app.
https://github.com/robert-hoekstra/be-course-18-19

**Comment by dandevri** [comment]
👋 Hi Robert, the link is added to the admin sheet.
