### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by StephanKop** [cmda-bt/be-course-18-19#106]
# Listing

## Name
Stephan Kop

## Class
tech 3

## Repo link
https://github.com/superstephan1/Project-Tech

## Summary
I turned my static html prototype into an express project. Converted all my html pages into ejs and made headers and footers as partials.

## Resources used
I found the first hour of this video very usefull. Walked me through the basic setup of express and ejs.
https://www.youtube.com/watch?v=gnsO8-xJ8rs&t=3603s

## Any thoughts?
Went pretty well in my opinion! The time description was pretty accurate. I spend about 5 hours doing this assignment. However if you don't have an html project ready it will take a lot longer. I want to make use of partials some more in my project, however i don't really know any smart places to use them.

**Comment by rijkvanzanten** [comment]
Heya 👋 

* Remove `.DS_Store` from the repo
* 
  ```
  What's
           going 
                 on 
                        here?
  ```
  https://github.com/superstephan1/Project-Tech/blob/master/views/matchafter.ejs
* Consider renaming `projectFiles` to something more descriptive of it's contents. Project files could also mean source code which it clearly isn't (`wiki-assets` or `docs` could be fitting)
