### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by OlafDs** [cmda-bt/be-course-18-19#107]
# Package

## Name
Olaf

## Class
Tech 3

## Repo link
https://github.com/OlafDs/Dating-app

## Summary
Today i installed some npm packages into my local folder where i be working on my dating app.
I made a .gitignore file where i hide de node_modules map, so people don't have to automatically download all the npm packages, but only donwload de code files.

And when i was done with all of that i pushed my local repo too my Github repo

## Resources used
https://www.npmjs.com/ - NPM packages
Stackoverflow & Github for guidance if i wanted to fix a problem 

## Any thoughts?
I struggled with the git pull and git push part, but after some research and testing i figured it out and it was pretty simple haha

**Comment by rijkvanzanten** [comment]
Good job 💯
