### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by NotAfr8Studio** [cmda-bt/be-course-18-19#108]
# Package

## Name
Mike van den Hoek

## Class
TECH 3

## Repo link
https://github.com/Fr3akyBeakyLike/Project-Tech

## Summary
I started looking up terms and looking through the examples. I tend to learn from video's and watched this youtube video: [NodeJS Tutorial 20 package.json file](https://www.youtube.com/watch?v=k1B9VIUkQmg)

## Resources used
[NodeJS Tutorial 20 package.json file](https://www.youtube.com/watch?v=k1B9VIUkQmg) and NPMjs.com

## Any thoughts?
Searching for an NPM usable for your job story was the thing I found difficult. Should I describe how to install the NPM's I use in the readme? I used a license for ISC cause I saw it coming by in my console and it lets people use my code freely, I don't know for sure if this is the best option.

**Comment by rijkvanzanten** [comment]
Good job 👍 

* I would remove the JS-Bootcamp folder from this repo, as it's unrelated to the project itself
* No idea what [this](https://github.com/Fr3akyBeakyLike/Project-Tech/blob/master/frontend/ElementsByTagName.js) is supposed to be, but it doesn't look like valid frontend code (as the name of the folder would suggest)
