### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Coenmathijssen** [cmda-bt/be-course-18-19#109]
# Package

## Name
Coen Mathijssen 

## Class
TECH 4

## Repo link
https://github.com/Coenmathijssen/blok-TECH/tree/master/Backend

## Summary
Already made the package, but updated it and fixed the devDevelopers dependencies. Also created a gitignore file.

## Resources used
Github, stackoverflow, Youtube, Google

## Any thoughts?
Fun exercise! Went pretty well

**Comment by rijkvanzanten** [comment]
See my comments on the listing issue
