### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Sanderoost** [cmda-bt/be-course-18-19#11]
# Package

## Name
Sander Oostenbrink

## Repo link
https://github.com/Sanderoost/blok-tech

## Summary
I did research to the npm packages and current dating apps.
I also made a list of possible job stories and i would like to build a chat function with your permission.

## Resources used
https://www.npmjs.com/ 
Tinder
Happn 
Lexa

## Any thoughts?
I'm having difficulties installing packages on my windows pc...

**Comment by rijkvanzanten** [comment]
Hey @Sanderoost!

Your repo is completely empty.. Is that intentional?

> I'm having difficulties installing packages on my windows pc...

What's wrong? What have you tried to fix it?

**Comment by dandevri** [comment]
😿

**Comment by Sanderoost** [comment]
Hey @rijkvanzanten!

There was something wrong with the permissions but i managed to fix it.
Now everything should be allright!

**Comment by rijkvanzanten** [comment]
Your repo is surprisingly similar to @markschuttehva's one including the same spelling quirks like this one: 

https://github.com/markschuttehva/Techproject/blame/master/README.md#L23
https://github.com/Sanderoost/blok-tech/blame/master/README.md#L10

what's up with that?

**Comment by Sanderoost** [comment]
thats odd.. I followed the guide and these files came out of it. 
And the readme i got from a former student, sorry for that.
I changed it up a bit.
