### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by Coenmathijssen** [cmda-bt/be-course-18-19#110]
# Package

## Name
Coen Mathijssen 

## Class
TECH 4

## Repo link
https://github.com/Coenmathijssen/blok-TECH/tree/master/Backend

## Summary
Created a server with node.js Express. It's serving CSS, JS, HTML and image files. Also rendering dynamic content with the help of EJS.

## Resources used
Github, stackoverflow, Youtube, Google

## Any thoughts?
I was really scared of this one, but it went better then expected.

**Comment by rijkvanzanten** [comment]
Heya 👋 

I'd recommend merging the two assignments. This Listing assignment is a continuation of the Package assignment. The next assignment will continue where listing left off, etc etc.

This is all looking very solid. Have you worked with Node / Express before?
