### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by robert-hoekstra** [cmda-bt/be-course-18-19#111]
# Package

## Name
Robert Hoekstra

## Class
214 (tech 3)

## Repo link
https://github.com/robert-hoekstra/BlokTech/tree/master/Website

## Summary
I installed NPM.
I Searched the NPM website for usable packages
Installed packages
created a .json

## Resources used
Only the course information and lectures.

## Any thoughts?
I know how to install the packages. However I find it hard to look for a good usable package as I am not familiar with NPM at all.

**Comment by rijkvanzanten** [comment]
The current state of your repo suggests that you're currently in the middle of overhauling it for the listing assignment. I have no clue what's going on here. Before you submit Listing, please refactor your folder structure a little bit more so it's easier to understand what is what 🙂 

I'll provide more in depth feedback once you submit the listing assignment

**Comment by robert-hoekstra** [comment]
Neither did I have a clue in what I was doing haha! However I am currently almost back on track. Will shoot a new issue when I got my folders done right.
