### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by robert-hoekstra** [cmda-bt/be-course-18-19#112]
# My Introduction

## Name
Robert Hoekstra

## Class
214 (tech 3)

## About me
26 year old barista wants to become a UX designer

## Goals
Get to know the basics of back-end

## Skill level
Noob

## GitHub username
robert-hoekstra

## GitHub repository
https://github.com/robert-hoekstra/BlokTech/tree/Master

**Comment by rijkvanzanten** [comment]
👋
