### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by patrick-ve** [cmda-bt/be-course-18-19#114]
# Package

## Name
Patrick van Everdingen

## Class
Tech 3

## Repo link
https://github.com/patrick-ve/festify

## Summary
I created a boilerplate for the Dating app feature.

## Resources used
Udemy, lynda.com and Traversy Media YouTube tutorials

## Any thoughts?
N.A.

**Comment by rijkvanzanten** [comment]
Am I going crazy or did you already submit this?

Ref https://github.com/cmda-bt/be-course-18-19/issues/103
