### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by kylebot0** [cmda-bt/be-course-18-19#116]
# Listing

## Name
Kyle Bot

## Class
TECH 4

## Repo link
https://github.com/kylebot0/Blok-tech/tree/master

## Summary
Express toegevoegd en een jade als template engine gebruikt.

## Resources used
Express en Jade

## Any thoughts?
-

**Comment by rijkvanzanten** [comment]
Heya 👋 

* Why do you have an additional folder? You can put all the files in the root of the repo
* Does this bit actually work like this?

https://github.com/kylebot0/Blok-tech/blob/ea1c05073936a0d6539f5f9a450b271e98b3c6e4/Project-tech/server.js#L13-L18

* Have you worked with Pug before? If not, what do you think of it?
* `npm start` is usually used to start the app in production. Consider renaming your `start` script to `dev`.
