### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Aidan98** [cmda-bt/be-course-18-19#117]
# Package
search_filter
## Name
Aidan Omwando

## Class
Tech 3

## Repo link
https://github.com/Aidan98/Project-Tech.git

## Summary
Een boilerplate gemaakt voor mijn filter feature.

## Resources used
https://www.npmjs.com/package/micromatch

## Any thoughts?
Aan het begin snapte ik totaal niet wat precies de opdracht was, maar dat we er uitleg erover kregen snapte ik het. Ik was vergeten een issue aan te maken.

**Comment by rijkvanzanten** [comment]
Heya!

* Put your project in a separate repo, or put the website in a separate branch. The two are unrelated, but the files are conflicting right now
* Remove `node_modules` from the repo

Please follow along with the actual assignments: https://github.com/cmda-bt/be-course-18-19/blob/master/week-1.md#description-1

If you fall behind this early, you'll have a very hard time recovering once the assignments get more difficult.
