### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by lennartdeknikker** [cmda-bt/be-course-18-19#118]
# Package

## Name
Lennart de Knikker

## Class
212

## Repo link
https://github.com/lennartdeknikker/dating-app-registration

## Summary
I created the boilerplate for a registration feature that can be used in dating applications.

## Resources used
[npm's documentation on package.json](https://docs.npmjs.com/files/package.json)

## Any thoughts?
-

**Comment by rijkvanzanten** [comment]
See my comments in the other issue 🙂
