### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by KarinCheng** [cmda-bt/be-course-18-19#119]
# Package

## Name
Karin Cheng

## Class
TECH4

## Repo link
https://github.com/KarinCheng/BlokTechDatingApp

## Summary
I created a simple boilerplate

## Resources used
https://github.com/remy/nodemon#nodemon
https://www.youtube.com/watch?v=ruieT3Nkg2M

## Any thoughts?
None

**Comment by rijkvanzanten** [comment]
Heya 👋 

* Add a useful readme (description, installation / usage instructions etc)
* Remove `node_modules` and `.DS_store` from the repo (`.gitignore`)
* Normally `npm start` is reserved for starting the application in production mode. Your `npm start` script however will start the application in development mode (using `nodemon`). Consider adding a `dev` script that will run the app with `nodemon`, and use `node` itself for the `start` script.
