### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by kriskuiper** [cmda-bt/be-course-18-19#12]
# Package

## Name
`Kris Kuiper`

## Repo link
[Project Tech repo Kris](https://github.com/kriskuiper/project-tech)

## Summary
`Added and set up the Readme. Added a Licence. Added .editorconfig. Completely set up npm and installed Nodemon as DevDependency. Still have to rewrite a Job Story so I can start to look for useful npm packages.`

## Resources used
* 'Choose a License' for finding the right license: https://choosealicense.com/licenses/mit/
* The BE-course repo for writing a descriptive licence.md: https://github.com/cmda-bt/be-course-18-19/blob/master/LICENSE.md
* Creative Commons for getting to know what the Attribution 4.0 International License actually means: https://creativecommons.org/licenses/by/4.0/

## Any thoughts?
`I still find it hard to write a solid and specific enough Job Story that I can work out for Project Tech and break that down into little pieces so I can start searching for useful npm packages.`

**Comment by rijkvanzanten** [comment]
Hey @kriskuiper! Good job so far.

Couple of small tips:
* Add `.DS_Store` to your `.gitignore` so it doesn't sneak into your repo later
* Consider moving the source code of your app into a folder separate from the configuration and repo files so it's a bit easier to navigate
* editorconfig +1
* What's the difference between `/index.js` and `scripts/main.js`?
* The license in your `package.json` is different from the license in the repo (ISC vs MIT)
* Try to adhere to your own editorconfig. You specified you're using 3 spaces (which is very uncommon, it's mostly 2 or 4) but you're using 4 spaces in the html files

**Comment by dandevri** [comment]
Looking good! 🎉  Nice job on setting up the configs. Can you add some linters as well?

Try to incorporate the small things @rijkvanzanten mentioned.
