### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by marissaverdonck** [cmda-bt/be-course-18-19#120]
# Listing

## Name
Marissa Verdonck

## Class
Tech4

## Repo link
[BlokTech_DatingApp](https://github.com/marissaverdonck/BlokTech_DatingApp)

## Summary
Gewerkt met HTTP, Express, EJS

## Resources used
Be course - Lecture 2/ Lab 2
Express - https://expressjs.com/en/starter/static-files.html */
EJS - https://www.npmjs.com/package/ejs

## Any thoughts?
Het installeren ging makkelijker dan ik had gedacht. De code juist in server.js schrijven was een beetje puzzelen en goed kijken naar de beschrijving.

**Comment by rijkvanzanten** [comment]
Heya, good job 🐻 

* Expand the readme a little bit with a description, installation, and usage instructions
* Remove the `.DS_Store` file from the repo
* Try to be very precise about your indentation. Files like [this one](https://github.com/marissaverdonck/BlokTech_DatingApp/blob/master/views/not-found.ejs) get very hard to read and maintain with the spaces and indents being all over the place
