### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by joanpadolina** [cmda-bt/be-course-18-19#122]
# Listing

## Name
Joan padolina

## Class
Block tech 4

## Repo link
https://github.com/joanpadolina/Project_Tech

## Summary
Worked with expres

## Resources used
The course from cmdbe used in this repo

**Comment by rijkvanzanten** [comment]
Heya, good job so far 💯 

* Try to keep all files and folders in the same language (`documentatie` vs `views`)
* Try to clean up your server file a bit. All the arbitrary white space and old pieces of code commented out make it a bit hard to read
* Remove the old `.html` files in the public folder once you're done translating them all into `.ejs` files
