### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by MarcKunst** [cmda-bt/be-course-18-19#123]
# Listing

## Name
Marc Kunst

## Class
Tech 4

## Repo link
https://github.com/MarcKunst/Project-Tech

## Summary
Assignments / homework week 2 (Express, EJS)

**Comment by rijkvanzanten** [comment]
Heya, good job 👍 

* You can cleanup the `server.js` file a bit by chaining the app calls:

```js
// before
app.use(express.static('static'))

app.get('/', (req, res) => res.send('Hello World!'))

app.get('/about', (req, res) => res.send('This is the about page'))

// after
app
  .use(express.static('static'))
  .get('/', (req, res) => res.send('Hello World!'))
  .get('/about', (req, res) => res.send('This is the about page'))
```
* Try to keep all the pages together, right now you have a html page in `static` and others rendered from EJS
* Did you test if this runs? There are a couple syntax errors from line 13 onwards in your `server.js` file that prohibits your server from running
