### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by Dejorden94** [cmda-bt/be-course-18-19#124]
# Listing

## Name
Dejorden Moerman

## Class
Tech 3

## Repo link
https://github.com/Dejorden94/Project-tech-datingapp

## Summary
set up a server, able to serve static files, 404 page added

## Resources used
express server example
https://expressjs.com/en/guide/using-template-engines.html
https://expressjs.com/en/starter/static-files.html
https://expressjs.com/en/starter/basic-routing.html

**Comment by rijkvanzanten** [comment]
* It's quite barebones
* Remove `node_modules` from the repo
* Update the readme with installation and usage instructions
* Try adding some more routes
* Your folder is called `static`, but in express you try to access `public`
* Make sure you won't fall behind this early on
