### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by lennartdeknikker** [cmda-bt/be-course-18-19#125]
# Listing

## Name
Lennart de Knikker

## Class
212

## Repo link
https://github.com/lennartdeknikker/dating-app-registration

## Summary
I switched to developing another feature than I initially wanted to make. I'll build a feature to change or add information/interests to the users profile. This way it's easier to implement progressive enhancement and practice the stuff we learn. 
* I designed and coded the new pages, 
* got the express server running,
* added routing 
* and split up my HTML in .ejs pages and partials.

## Resources used
* https://scotch.io/tutorials/use-ejs-to-template-your-node-application
* the lectures

## Any thoughts?
I got a little behind, because I couldn't really work with the feature I originally wanted to make and had to start over for a bit. I'm hoping to get back on track by the end of the week.

**Comment by rijkvanzanten** [comment]
Heya! This is looking pretty good so far 🙂 

* I notice you have the same html in every single page ejs 
  ```html
  <!DOCTYPE html>
  <html lang="en">
  ```
  You could add these two lines into your `head` partial so you don't have to repeat it in every page template
* I'm not entirely sure what you're trying to do here: https://github.com/lennartdeknikker/dating-app-registration/blob/master/server.js#L5 but be careful with this kind of global state. This flag (true/false) is not specific to the user opening the page, but is global for the whole server. Keep that in mind while developing the functionality of your app.
* Same thing applies to the `idCounter`, again i'm not totally sure what you're trying to achieve, but you're incrementing it everytime _anyone_ accesses the `change` route
* `.listen()` is asynchronous. You should use the callback function so the console log only shows up when the server is actually listening:

https://github.com/lennartdeknikker/dating-app-registration/blob/c50a4c4cadb7b5e6a19361273c563ade24472c73/server.js#L32-L33

```js
.listen(3000, function() { console.log('listening!'); });
```
