### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by robert-hoekstra** [cmda-bt/be-course-18-19#126]
# Listing

## Name
Robert

## Class
214 (Tech 3)

## Repo link
https://github.com/robert-hoekstra/BlokTech/tree/master/testserver

## Class
214 Tech 3

## Summary
Hi Rijk, back at it again.
I finally managed to setup an environment with express and EJS as templating engine.
I understand the functionality of the package.json and the commandline is getting fond on me.
The repo I added in this issue directs you to a subfolder within my main repo.

Currently I am separating my static website and dynamic for learning purposed. However I will merge both of them into one dynamic version ofcourse.

I will write a readme when my feature is created. As from this moment I am still in the middle of nowhere of where to start. I want to give my user the abillity of uploading and resizing/cropping their avatar.

## Resources used
https://expressjs.com/en/starter/installing.html
https://scotch.io/tutorials/use-ejs-to-template-your-node-application
https://www.npmjs.com/package/express-fileupload
https://medium.com/startup-frontier/40-npm-modules-we-can-t-live-without-36e29e352e3a

And I had some handlebars tutorials as wel. But I dropped it as I quite needed the instructions from the lectures.

## Class
214 Tech 3

## Any thoughts?
I found the whole npm, node and express part really hard. Untill two days ago it finally I could finally say to myself that I am getting the basics of this system.

## Class
214
Tech 3

**Comment by rijkvanzanten** [comment]
Heya, good job 💯 

* Get rid of node_modules and .DS_Store files in your repo
* Add a readme explaining what your app is, what it does, and how to get it setup and running
* Add a license file to the repo
