### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by woutarb** [cmda-bt/be-course-18-19#129]
# Listing

## Name
Wouter Bijnsdorp 

## Class
Tech 3

## Repo link
https://github.com/wouterBijns/ProjectTechRepo

## Summary
Een express server aan de slag gekregen

## Resources used
Example in the github

## Any thoughts?
Had wat moeite met beginnen

**Comment by rijkvanzanten** [comment]
Heya!

* Try using a templating setup in your server.js file
* Get rid of your static html files if you're not using them anymore.
* I would put the wiki images inside your project, instead of splitting them up on an equal hierarchy level
