### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by StefanGerrits2** [cmda-bt/be-course-18-19#13]
# My Introduction

## Name
`Stefan Gerrits`

## Class
`211 / Tech - 1`

## About me
`I'm looking forward to follow this class.`

## Goals
`Learn more about Backend Development in general`

## Skill level
`Beginner`

## GitHub username
[Profile](https://github.com/StefanGerrits2)

## GitHub repository
[Repository](https://github.com/StefanGerrits2/datingwebsite-bloktech)

**Comment by dandevri** [comment]
Thanks!
