### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by StefanGerrits2** [cmda-bt/be-course-18-19#14]
# Package

## Name
`Stefan Gerrits`

## Repo link
[Repository](https://github.com/StefanGerrits2/datingwebsite-bloktech)

## Summary
`I created a boilerplate for the feature I'm going to make. This includes a package.json with name, version, dependencies and other metadata. I picked some packages from npm that I'm probably going to use, and installed them. I also added a gitignore file so it doesn't upload the node_modules folder. And last but not least, I added a README with a license.`

## Resources used
https://choosealicense.com/ To choose a license.
https://www.npmjs.com/ To select and install the correct packages.

## Any thoughts?
`The most difficult part was to find the correct packages that I think I'll need. I think it will take some time before I can actually select the right packages to use for my job story.`

**Comment by rijkvanzanten** [comment]
Hey @StefanGerrits2! Good job 🙂 

* You should add `.DS_Store` to the `.gitignore` file so those annoying files don't end up in the repo later
* Consider moving the application source files into a folder so they don't get mixed with the "repo" files 
* Try to make clear what code is server (Node) and what is client (browser). `index.js` doesn't really indicate which of the two it is (which will get very confusing later on!)

**Comment by dandevri** [comment]
Looking good! 🎉
