### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by nlvo** [cmda-bt/be-course-18-19#15]
# Package

## Name
Lien Vo

## Repo link
[Dating app](https://github.com/nlvo/dating-app)

## Summary
Initialised a repository, added a licence, editorconfig (which I'll probably update somewhere down the road) created a boilerplate with packages which I'm going to need for the dating app.

## Resources used
A bit from memory and from the live demos and last but not least a little bit from [learnyounode](https://github.com/workshopper/learnyounode).

## Any thoughts?
Breaking a job story apart in order to find the correct packages, was something I struggled with. And also the [job stories](https://github.com/nlvo/project-tech/wiki/Week-2#job-stories) themselves, but that's another story.

**Comment by rijkvanzanten** [comment]
Hey @nlvo! Good job! 😄 

The only tip I have would be to _not_ list the required packages on readme.md. GitHub will actually render a full dependency graph based on the package files already: https://github.com/nlvo/dating-app/network/dependencies and doing it manually in the readme is really hard to keep up to date!

**Comment by dandevri** [comment]
Good job on the `.editorconfig` 🎉  Don't forget to also set-up an [extension](https://editorconfig.org/#download) for your editor!
