### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by markschuttehva** [cmda-bt/be-course-18-19#16]
# Package

## Name
Mark Schutte

## Repo link
https://github.com/markschuttehva/Techproject

## Summary
Npm packages geïnstalleerd, 
Package.json file aangemaakt via de terminal
License toegevoegd aan het bestand
.gitignore bestand aangemaakt zodat node_modules niet mee gaat tijden het versturen

## Resources used
https://choosealicense.com/licenses/mit/
https://www.npmjs.com/package/nodemon
Danny natuurlijk :wink:

## Any thoughts?
Thoughts: Leuke leerzame eerste opdracht hoe om te gaan met Npm packages.
Feedback: Graag eerder kijken naar de jobstories, hierdoor zouden we al eerder kunnen kijken naar de juiste packages die we hiervoor konden gebruiken.

**Comment by rijkvanzanten** [comment]
Hey @markschuttehva!

* Try installing and importing a module into the javascript file
* The license in the repo is different from the one listed in the package.json file
* The readme is a bit messy. I'm assuming you copy pasted a template and updated parts of it to fit. 
  * The packages included section misses the link, the git clone command is wrong
  * You're mixing English and Dutch 
  * There's a typo in the markdown, which makes it render incorrect (`#Install guide`)

**Comment by dandevri** [comment]
Try to incorporate the feedback from @rijkvanzanten before the next lab!

I'm going to take a look at the job stories in just a sec 👀
