### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Plous01** [cmda-bt/be-course-18-19#17]
# Package

## Name
Paulien

## Repo link
[Plous01](https://github.com/Plous01/ProjectTech)

## Summary
I searched for some packages for my project and I tried to install a few of them. For this project, I installed the nodemon and camelcase package. Also, I started working with Node.js

## Resources used
https://www.npmjs.com

## Any thoughts?
At the beginning, I had some difficulties with this exercise, but the live demos were very useful!

**Comment by rijkvanzanten** [comment]
Hey @Plous01! Good job 😄 

Thanks for including the job stories as PDF files.

* `npm start` will run the application in development mode. Consider adding a `npm run dev` for development and using `npm start` for actually starting the application with Node

**Comment by dandevri** [comment]
Looking good! 🎉 

You can also attach those `.pdfs` in your Wiki page, I would prefer that so I don't have to go looking for them in your repo. It's also a good practice to keep any documents and files related to the project in a `docs` folder.

**Comment by Plous01** [comment]
Thanks for the feedback! I will also try to add a `npm run dev`.
