### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by chriskes** [cmda-bt/be-course-18-19#18]
# Package

## Name
[Chris Kesarsing](https://github.com/chriskes)

## Repo link
[Repo dating app](https://github.com/chriskes/Dating_app)

## Summary
Had a lot of trouble using connecting my VScode and github, somehow it is connected but commiting doesnt load anything up to my repo in Github. All and all, difficult but doable. Created a repo on a desktop folder where I downloaded the package and made the index.js and just uploaded it the noob way via de website. 

## Resources used
Some youtube tutorials, live demo from memory

## Any thoughts?
It was a bit vague, but after trial and error and reading/watching it will become clearer. Next week going to ask someone to help me with the gits how to upload via VS code.

**Comment by rijkvanzanten** [comment]
Hi @chriskes!

> Had a lot of trouble using connecting my VScode and GitHub

I would highly recommend learning Git on the command line first so you grasp the underlying theory before jumping into using a GUI tool. 

> somehow it is connected but commiting doesnt load anything up to my repo in Github

Committing will only create a new commit on your local history, you still have to push it up to the remote repo (GitHub) for it to show up.

Other feedback:
* Add a `.gitignore` file so you don't accidentally upload `node_modules` or `.env` files
* The packages mentioned in the readme don't match the packages used in the package.json file
* Add a license to the repo
* I'd recommend changing the title in your repo from "READ ME" to "Dating App" or something more descriptive. I know it's the readme by the filename (and the fact that GH shows)

**Comment by dandevri** [comment]
Try to incorporate the feedback from @rijkvanzanten before the next lab! There are quit some things missing and/or incomplete.

Indeed, I would prefer you use Git from the CLI. Feel free to ask for help in the next Project Tech class.
