### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by junecha** [cmda-bt/be-course-18-19#19]
# Package

## Name
`Chun`

## Repo link
https://github.com/ChunningTatum/Blok_tech

## Summary
`Heb het begin van een Json file gemaakt, ook een begin van een README file en een License gemaakt.
Verder heb ik een wiki gemaakt met de research en job stories. Moet zelf nog even wat tijd in stoppen om de boilerplate goed te maken.`

## Resources used
`What resources did you use?`

## Any thoughts?
`Let us know what you thought of the homework, and give us any feedback. What parts did you find difficult?`

**Comment by rijkvanzanten** [comment]
Hey @ChunningTatum!

Please fill out the issue template as requested next time.

* The license in the repo (GPL 2) is different from the one mentioned in package.json (GPL-3)
* Good job on researching the different licenses :) 
* I would recommend keeping files all lowercase (`Index.js` -> `index.js`). Certain systems don't handle cases in filenames well
* Try installing and requiring a package

**Comment by dandevri** [comment]
Try to incorporate the feedback from @rijkvanzanten before the next lab! There are quit some things missing and/or incomplete.
