### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by MartijnKeesmaat** [cmda-bt/be-course-18-19#2]
# Package

## Name
Martijn Keesmaat

## Repo link
https://github.com/MartijnKeesmaat/dating-app

## Summary
This week I started learning Node.js and initialized a repo for the dating app feature. The challenge I set for myself was to use the terminal for git, learning Node.js, adding files,  and navigating. So far I had to use a UI once because of a repo that didn't want to work together.

## Resources used
I used [Learn You Node](https://github.com/workshopper/learnyounode) as an introduction to Node.

## Any thoughts?
The time that was set for the [Package feature](https://github.com/cmda-bt/be-course-18-19/blob/master/week-1.md#package-feature) is 6 hours. I'm not sure if I skipped something, but I didn't come close to that time. I thought it was really fun working in the terminal, using git in the terminal and then seeing in appear on Github was really cool.

**Comment by rijkvanzanten** [comment]
Heya!

I noticed you tried displaying an image in the readme by embedding a temporary Dropbox link. Dropbox will automatically generate the image preview links to ensure that random people can't guess the links. I believe you can make a file publicly accessible to achieve a similar thing though.

There were some other small things I noticed:

* You can replace
```json
  "repository": {
    "type": "git",
    "url": "git+https://github.com/MartijnKeesmaat/dating-app.git"
  },
```
with `"repository": "MartijnKeesmaat/dating-app"` for GitHub hosted repos

* The license in your repo is different from the one listed in`package.json`
* You list `node_modules` twice in `.gitignore`
* You might want to consider adding `.DS_Store` to the `.gitignore` file (assuming you're working on a Mac)

**Comment by rijkvanzanten** [comment]
Also, try requiring a module in your index.js file and run it with Node! You're 95% of the way there

**Comment by MartijnKeesmaat** [comment]
@rijkvanzanten Hey Rijk, thanks for your feedback. I didn't know that about Dropbox, but I had trouble with that issue before, so that's really useful that you mention it.

**Comment by dandevri** [comment]
> []...is 6 hours.  I didn't come close to that time. 

You can always work ahead or pick a topic you want to explore further. 

Additionally you can: 
* Look into other configs and linters
* Use more features of git or GitHub such as consistent comment messages, contributing guidelines, licenses etc.
* Expand on your `readme.md`, currently it doesn't include the instructions to install your project locally. Have a look at [The Art of Readme's](https://github.com/noffle/art-of-readme).
* Look into `lock` files. What does the `package-lock.json` do?
