### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by deinca** [cmda-bt/be-course-18-19#20]
# Package

## Name
`Deiver Zamora Cortez`

## Repo link
[Repository](https://github.com/Loquino/pt-course-18-19)

## Summary
`In this repository I have made my own start package inventory but I have also include a Wiki with background information about my project`

## Resources used
In general the npm website where I find this package:
[express-fileupload](https://www.npmjs.com/package/express-fileupload)
YouTube for the license
[Writing a readme: adding a license](https://www.youtube.com/watch?v=gJZGLZSzP_I)

And to recap what .girignore does
[Part 4 - How to use .gitignore [Git-ing Started with Git Series]](https://www.youtube.com/watch?v=0WfDe51pUU0)

## Any thoughts?
`Well i still struggle with the Github, I am like a noob that is using Github graphical UI like a Wordpress site. What I mean is I decide to not use the terminal (git) to commit the changes in my repository. But at the other side I think that preparing and installing the packages via the terminal went well. Futher I really have any feedback for now`

**Comment by rijkvanzanten** [comment]
> I decide to not use the terminal (git) to commit the changes in my repository

Why is this? IMO it's actually easier to use the terminal, as it makes you more familiar with the actual Git flow (makes it easier to debug issues!)

* There's a couple of empty files (package/.editorconfig, package/index.js)
* You don't need to list the exact dependencies to install in the readme. That's what the package.json file is for. Running `npm install` will read the package.json file and use the dependencies listed in there
* You're only ignoring the `node_modules` folder in the root of the repo. However, you're package (and package.json file) are in a folder. This means that the `node_modules` that will be created in the `/package` will still be staged for a commit
* Did you take a look at [Multer](https://www.npmjs.com/package/multer) too?

**Comment by dandevri** [comment]
Indeed, I would prefer you use Git from the CLI. Feel free to ask for help in the next Project Tech class. Try to incorporate the feedback from @rijkvanzanten before the next lab! There are quit some things missing and/or incomplete.
