### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by GiovanniDw** [cmda-bt/be-course-18-19#21]
# Package

## Name
Giovanni

## Repo link
[Giovanni's Project Repo](https://github.com/GiovanniDw/pt-course)

## Summary
I didn't know what dependencies to pick so I've added some dependencies and tried to get m up and running

## Resources used

[20-nodejs-modules-you-need-to-know](https://www.creativebloq.com/features/20-nodejs-modules-you-need-to-know).  
[9-npm-packages-to-explore-in-your-next-node-js-application-2018](https://hackernoon.com/9-npm-packages-to-explore-in-your-next-node-js-application-2018-ec4aac0ca723)
[beginners-guide-to-mobile-web-development/top-5-npm-packages-and-their-uses](https://medium.com/beginners-guide-to-mobile-web-development/top-5-npm-packages-and-their-uses-e4e5194b4649)

## Any thoughts?

Only difficulties that I had is still what dependencies to pick.

**Comment by rijkvanzanten** [comment]
Hey @GiovanniDw! Good job 😄 

* Using a template for the `.gitignore` file is a good idea. However, there's a bunch of files ignored that will never be in your repo in the first place (`.dmg / `.exe` etc)
* Move your client code away from the server code by putting it in a separate folder
* Add a license to the repo

> I didn't know what dependencies to pick

Once you start building the actual application, you'll run into things you need soon enough 😄

**Comment by dandevri** [comment]
Looking good! 🎉  Good job on trying out the different packages. Try to incorporate the feedback from @rijkvanzanten before the next lab! 

This isn't the first time you handed in your assignments **late**, next time you won't receive detailed feedback.
