### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Aronsmit2** [cmda-bt/be-course-18-19#23]
# Package

## Name
`Aron Smit`

## Repo link
`https://github.com/Aronsmit2/BlockTech_datingApp`

## Summary
`I didn't know any dependencies yet, so I installed camelcase and nodemon.`

## Resources used
`https://www.npmjs.com?`

## Any thoughts?
`I didn't understand the exercise completely in the beginning, but the live demo helped a lot. `

**Comment by dandevri** [comment]
Hi Aron!

This assignment is not on-time but here's some feedback:

* Lots of files are empty: you installed `camelcase` but don't use it inside `main.js`. Your `.editorconfig` is also empty.
* The license in your `package.json `file is different from the one in the repo
* Try splitting up the front end code from the back-end logic. You now have a folder `scripts`. Is that server-side or client-side?
