### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Kalemis** [cmda-bt/be-course-18-19#24]
# Package

## Name
Artemis

## Repo link
[Dating app repository](https://github.com/Kalemis/project-tech)

## Summary
I created a boilerplate for a dating app in which you get to know a person before seeing their photo. By talking to each other the person's profile picture will become less and less vague. By the time the picture is clear, you already got to know the person quite a bit! 

The packages I thought were useful are:
- Express: for routing
- Validate string: for forms
- Chat engine: to create a chatbox

The other packages installed are to test and find out how to make them work. I will probably delete them in the next assignment.

## Resources used
[To look up any packages](https://www.npmjs.com/)

Had a tiny difficulty importing the package the way I'm used to:
[This helped](https://stackoverflow.com/questions/39436322/node-js-syntaxerror-unexpected-token-import )

[For help with script in package.json](https://docs.npmjs.com/misc/scripts)

## Any thoughts?
First of all, I'm sorry the issue is not on time. Due to illness I could only finish it now. I still wanted to hand it in and I hope I can still get some feedback as I always find it very helpful.

I actually find it quite difficult to find the packages I'm going to use. I think I will probably add more on the go but think this is already something to start with.

**Comment by dandevri** [comment]
Hi Artemis!

This assignment is not on-time but still, here's some feedback:

* Try to use the [`wiki`](https://help.github.com/en/articles/about-wikis) feature on GitHub so your repository doesn't get cluttered with documents. If you want to do so, it's best practice to put them all inside a `doc` folder.
* There is a license in your `package.json` but the repository itself doesn't have a license!
* You include `index.js` inside `index.html` but this code is server-side. `require` doesn't work inside of the browser and shouldn't be included inside of `index.html`.

Good job on the packages inside the `.json` file differentiating devDependencies.
