### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by iamDistractech** [cmda-bt/be-course-18-19#25]
# Listing

## Name
Thijs Spijker

## Repo link
[Project Tech](https://github.com/iSirThijs/pt-tech/)

## Summary
I made my static feature from project tech dynamic on the server by adding routes. 

## Resources used
This Repo from Backend
Express Documentation
EJS documentation

## Any thoughts?
Once I understood some concepts, it was quite easy to start and get it done

**Comment by rijkvanzanten** [comment]
I'm not too sure how I feel about the utils setup 🤔 

It's great to clean up the `/server/index.js` file (and you did a great job on that), but I'd recommend using a more traditional `routes` setup. That way it's way easier for external devs to get into your codebase. Using an alternative structure, like this custom utils game library object with all the routing it can and will cause confusion.

Same goes for the `source` folder. I thought it was un-bundled source files for your website output, but it's both `dist` publicly available files in `static` and the views that build up the HTML. I would've expected `views` to be in `server`.

So overall great job on the code and functionality, but do re-consider some of the folder naming and structure 🙂

**Comment by iamDistractech** [comment]
Thanks for the feedback.. 

@dandevri suggested I take a look at MVC. So that's what I did. I've read up about it and tried to get my folder structure set-up in that way.. 

Source contains the View
Utils contains the Controllers 

and I don't think I have a model yet, since we don't have the database yet..

I took a lot of reference from this diagram:
![mvc](https://cdn-images-1.medium.com/max/2000/1*4SxbmCrI5YVp1Uyj1Jstsg.png)

@rijkvanzanten did I understand it correctly?

**Comment by rijkvanzanten** [comment]
Ah gotcha. In that case, I'd recommend going with something like

```
models/
views/
controllers/
utils/
routes.js
```

`utils` is normally used for small individual utility functions you re-use a whole lot, instead of like routing logic, that's what threw me off primarily.

**Comment by rijkvanzanten** [comment]
I think there's a bunch of express-mvc boilerplates available. Maybe you can take a look how others are solving this problem, and learn from that too 😄

**Comment by iamDistractech** [comment]
Using `utils` was indeed a bit confusing. I've looked into it some more and did some research. I've changed the folder structure once more 😅. Models is still missing, waiting for next week (with database etc).

`utils` is now `controllers`
