### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by emmaoudmaijer** [cmda-bt/be-course-18-19#27]
# Listing

## Name
Emma Oudmaijer

## Repo link
https://github.com/emmaoudmaijer/datingsite 

## Summary
I Created a server that handles routes and serves static files in Node.js. The static server contains a couple of different routes (login, about, homepage, 404). For this exercise i used template engine pug for creating different routes.

## Resources used
https://www.npmjs.com 
https://pugjs.org/api/getting-started.html
http://expressjs.com 

## Any thoughts?
It was a difficult exercise but i liked it.

**Comment by rijkvanzanten** [comment]
Heya! Good job.

Try to take some time to clean up your repo. There are a lot of different experiments and files left that you don't necessarily need right now. That will add a lot of confusion!

But also in your `server.js` file, your start of with some seemingly random previous experiments:

```js
var camelcase = require('camelcase');

console.log(camelcase('hello-world'));

var nodemon = require('nodemon');

console.log(nodemon('hello-world'));
```

Also, `node_modules` and `.DS_Store` made it into your repo unfortunately. Also I think `dating-website` is an older version of what turned into `static`?

Just by cleaning up the repo will make it a whole lot easier for you to work on your project as well!
