### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by cirogoud** [cmda-bt/be-course-18-19#28]
# Listing

## Name
Ciro Goudswaard

## Repo link
https://github.com/cirogoud/backend

## Summary

* Add pug files
* Create routes
* Looked into pug more

I made some decent progression because now I get to understand Pug more.

## Resources used
I used the resources from the github files and google.

## Any thoughts?
I found it difficult to begin with Pug because it was new and I didn't understand it at all. Now I got to work with it and learned to connect it all to each other I'm getting somewhere.

**Comment by rijkvanzanten** [comment]
Heya!

Good job 👍 

* Consider moving the partials into their own folder
* You use tabs here: https://github.com/cirogoud/backend/blob/a1296a88aedfaebbd2d2ef667dc35d8162532470/index.js#L5-L10, but use spaces in the rest of your work. Did you copy that section from somewhere?
