### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by Sajjad0405** [cmda-bt/be-course-18-19#29]
# Listing

## Name
`Sajjad Ali`

## Repo link
https://github.com/Sajjad0405/dating-app/

## Summary
`Pug geinstalleerd, static files, views and partials gemaakt`

## Resources used
- Pug docs
- Express docs
- Danny

**Comment by rijkvanzanten** [comment]
Heya!

By the looks of it, you got into trouble with merge conflicts:

<img width="130" alt="image" src="https://user-images.githubusercontent.com/9141017/54364025-7ec2eb00-4642-11e9-90f7-9a38d4be5302.png">

* Overall this is looking pretty good 😄 
* Consider removing the `profile.html` file so there's no confusion possible on what it's for
* Consider moving the partials into the views folder, as partials are parts of views
