### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Root-ish** [cmda-bt/be-course-18-19#3]
# Package

## Name
Rick van der Straeten

## Repo link
https://github.com/Root-ish/dating-repo

## Summary
I initialised a repo for my dating app feature and uploaded a README.md and a .gitignore file. I've used the Github desktop app before and found it interesting to see how actions like push and pull where executed using the Terminal.

## Resources used
I used a few resources : [Medium introduction to nam scripts](https://medium.freecodecamp.org/introduction-to-npm-scripts-1dbb2ae01633), 
[Microsoft git ignore files](https://docs.microsoft.com/en-us/azure/devops/repos/git/ignore-files?view=azure-devops&tabs=visual-studio), The learn you node environment and lastly I used the [Lodash package](https://www.npmjs.com/package/lodash)

## Any thoughts?
The Learnyounode was a bit hard but I managed after a few tries and Youtube tutorials. The package was fun to connect with the GitHub environment. Can't what to install and import Webpack and such libraries.

**Comment by rijkvanzanten** [comment]
Hey Rick!

* I'd recommend you put the "repo files" in the root of the project `/` and put the actual files that make up your project into a folder like `src` or `app`. That way, you won't end up with a huge list of intertwined files that have different purposes
* You might want to add `.DS_Store` to your `.gitignore` file (assuming you're using a Mac) 
* As you probably noticed based on the comments in [`index.js`](https://github.com/Root-ish/dating-repo/blob/master/index.js) client side JavaScript doesn't (normally) have access to `node_modules` nor should you (in most cases) upload `node_modules` to a web server for public use. Instead, you should take a look at a bundler like [Parcel](https://github.com/parcel-bundler/parcel) or [Webpack](https://webpack.js.org) to bundle the modules into a single JS file

**Comment by rijkvanzanten** [comment]
If you'd like to make the index.js import work, you can try running it with Node! Node will automatically use `node_modules` as the source of modules (hence the name).

**Comment by dandevri** [comment]
To expand on the feedback of @rijkvanzanten 

* What's the reason for using `Yarn` over `NPM`? You can use either but ask yourself why you are using it. If you can, please document that in your wiki so I can read your rationale.
* Same goes for `parcel` or `webpack`. Why do you want to use those bundlers? Is that one of your learning goals?
