### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [cmda-bt/be-course-18-19#30]
# Listing

## Name
Rowin

## Repo link
https://github.com/Rowin206/DatingApp

## Summary

I made a lot of progress. At the begin, it was not clear how I should start. That's why I started with searching about express server on Google and Youtube.

I went through the assignment again, it was already more clear what to do. The example of the express server helped me as well! I started to copy small lines of code to see what they were doing. I got a lot of errors, because they needed different code. By solving the errors I really learned a lot.

## Resources used
Express server example
https://www.youtube.com/watch?v=BNikS1X5NVk
https://expressjs.com/en/guide/routing.html
https://scotch.io/tutorials/learn-to-use-the-new-router-in-expressjs-4
https://expressjs.com/en/api.html
https://www.tutorialspoint.com/expressjs/expressjs_routing.htm

## Any thoughts?
The start was a little bit hard, because there was no explanation. On the other hand, it did help me to understand what I was doing. 

Later on I made it even more difficult for myself than expected because I wanted to use and understant routing, because I didn't like it how much code there was in the index.js file.

**Comment by rijkvanzanten** [comment]
> I wanted to use and understant routing, because I didn't like it how much code there was in the index.js file.

Good one! In general multiple smaller files are easier to work with than one big one.

As you've probably noticed, it does help a lot in the organization of your codebase (from my own archives):

<img width="206" alt="image" src="https://user-images.githubusercontent.com/9141017/54363250-f132cb80-4640-11e9-8b86-a1922a5a8a59.png">

There are a couple more tricks you can use to get rid of a few extra lines if you like:

1. Chain the `app.bla()` methods:

```js
// before
app.use(routes)
app.use(aboutRouter)
app.use(login)
app.use(users)

// after
app
  .use(routes)
  .use(aboutRouter)
  .use(login)
  .use(users)
```

2. Don't instantiate express into a variable:
```js
// before
const app = express();

app
  .use(routes)
  .use(aboutRouter)
  .use(login)
  .use(users);

// after
express()
  .use(routes)
  .use(aboutRouter)
  .use(login)
  .use(users)
```

3. Require the routes inline:
```js
// before
var routes = require('./routes');
var aboutRouter = require('./routes/about')
var login = require('./routes/login')
var users = require('./routes/users')

app.use(routes)
app.use(aboutRouter)
app.use(login)
app.use(users)

// after
app.use(require('./routes'));
app.use(require('./routes/about'))
app.use(require('./routes/login'))
app.use(require('./routes/users'))
```

You can use these same tricks in the routers as well 🙂

**Comment by RowinVanAmsterdam** [comment]
Ah! This makes so much sense now! Thank you, I just updated the code like your examples.

Edit: 
Oh and I shared this with some classmates as a pull request :)
