### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by Sanderoost** [cmda-bt/be-course-18-19#31]
# Listing

## Name
Sander Oostenbrink

## Repo link
https://github.com/Sanderoost/blok-tech

## Summary
I installed pug and express and made routes to the pug files.

## Resources used
i worked together with Ciro Goudswaard so some functions might be similar.
https://pugjs.org
https://expressjs.com/
https://stackoverflow.com/questions/6528876/how-to-redirect-404-errors-to-a-page-in-expressjs

## Any thoughts?
The live demo helped me a lot to complete this lesson. 
Im actually starting to get the hang of it!

**Comment by rijkvanzanten** [comment]
> Im actually starting to get the hang of it!

Yaaaaaaaaaaaasssss 💪 

* There are a few nitpicky code style issues you can fix: indentation, missing white line, semicolons vs no semicolons etc
* What do you think of Pug? Like it? Would you use it again in the future?

Good job overall 👍

**Comment by Sanderoost** [comment]
Hi Rijk,

Thanks for the feedback!
Pug was actually a little difficult at first because of the spacing and tabbing syntax it uses, but it did get easier over time!
I would probably go for pug again in the future or try ejs since it looks a lot like regular html.
