### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by chriskes** [cmda-bt/be-course-18-19#33]
# Listing

## Name
[Chris Kesarsing](https://github.com/chriskes)

## Repo link
[My repo!](https://github.com/chriskes/Dating_app)

## Summary
The live demo helped me out alot! After following the demo I reviewed the code piece by piece and try to understand it and I'm close to understand how setting up a express server with views and static files works. Still have to include dynamic data rendering with partials but I know that Pugjs is not the framework for that, I read that Handlebars works better for this, will check this out soon. 

## Resources used
Express and Pugjs guides. Live demo from Danny, Stackoverflow

## Any thoughts?
It was moderatly challenging, so I had fun with it :)

**Comment by rijkvanzanten** [comment]
Heya! Good job :) 

>  I had fun with it :)

Most important thing!

* I like your style of comment headers (the `//---------- TITLE ----------//`)!
* Nitpick: you use semi-colons after every line, except when you have a multiline block:

```js
app.use('/static', express.static('static')); // semi-colon

app.get('/', function (req, res) {
  res.render('index.pug')
}) // no semi-colon
```

What did you think of Pug? Like it? Dislike it? Why?

**Comment by chriskes** [comment]
Thanks for the feedback! I will take a look at my semi-colons. As for Pug, I like it. The syntax is something getting used to but the mixins are very cool for rendering dynamic content. But for now I'm using EJS for this is in the example, and JavaScript in HTML is pretty cool. Also something getting used to!
