### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by cenikk** [cmda-bt/be-course-18-19#34]
# Listing

## Name
Kaan Cenik

## Repo link
https://github.com/cenikk/datingapp

## Summary
I've installed ExpressJS in my dating-app, ExpressJS basically helps me manage everything, from routes, to handling requests and views. With Express you can also choose a templating language (like Pug, Mustache, EJS, Jade etc.), which enables you to use static template files in your application, I've chosen to go with EJS since it looked very easy to understand from the slides. 
With my setup being ready, I've made my first few routes in my application (index, about, register and 404page). To test EJS out, I've made a testData array in my index.js and looked how I can include it in my .ejs files.

## Resources used
To help me understand express more, I've mainly used: [npmjs/express](https://www.npmjs.com/package/express), 
and the getting started guide on [expressjs-guide](http://expressjs.com/)

To learn how EJS works, I've used the slides on lecture-2: [EJS-slides](https://docs.google.com/presentation/d/1uT6CVMdNig-I9oSwEHI-QiadINH96HYyRC-BIIPxhSI/edit#slide=id.g4e3b0a72ee_0_28),
as well as the getting started guide on [EJS-install](https://ejs.co/#install)

## Any thoughts?
For me, it was very difficult to serve my static files at first, since I couldn't connect my .ejs files to my css in my static files. I went through all the slides to find an answer and when I finally did, I copied (what I thought to be) the solution and it still didn't work. Luckily at the "Extra resources" section, there was a link towards Static files where I finally managed to find the answer on how to serve your static files in Express, provided with examples and descriptions.

**Comment by rijkvanzanten** [comment]
Heya! Good job :)

It can be quite tricky to keep track of what goes where in terms of backend vs front-end. Glad to see you got it to work eventually though!

* Try improving the readme a little bit. Add a description, plan of execution, things of that nature.
* Good usage of comments 👍 
* Consider removing the `index.html` static file so there's no confusion which one is being used (`index.html` vs `index.ejs`)
