### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by nlvo** [cmda-bt/be-course-18-19#35]
# Listing

## Name
Lien Vo

## Repo link
[dating app repository](https://github.com/nlvo/dating-app)

## Summary
Created a server with basic routes. And tried pug and handlebars out, in the end I chose to use pug.

## Resources used
[Expressjs](https://expressjs.com/), [pugjs](https://pugjs.org/api/getting-started.html), [davidburgos.blog](https://davidburgos.blog/how-to-handle-404-and-500-errors-on-expressjs/ ) and last but not least the live demos.

## Any thoughts?
I'm stil trying to figure out a good but simple folder structure to use in order to keep everthing organised, this also applies to the routes which are now located in the index.js. But other than that it was doable.

**Comment by rijkvanzanten** [comment]
Hey there!

* Why do you switch from arrow functions to "regular" functions at a certain point in your `index.js` file?
* Try to clean up your css file a bit. The indentation is seemingly switching between tabs and spaces arbitrarily

Overall, looking good 👍
