### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by Plous01** [cmda-bt/be-course-18-19#36]
# Listing

## Name
Paulien

## Repo link
[My repository](https://github.com/Plous01/ProjectTech)

## Summary
I created a server with some basic routes (home, about, login and error). I have used the template engine pug for creating different routes.

## Resources used
* express.com
* pug.com
* stackoverflow.com

## Any thoughts?
For me, this exercise was quite challenging, but I like a challenge:) I am going to spend more time on this subject, so I gain a better understanding of it.

**Comment by rijkvanzanten** [comment]
Hey there! Good job

Have you tried running your server? Just by the looks of the repo the `/` endpoint wouldn't work right now does it?

**Comment by Plous01** [comment]
Hi Rijk! 

I can run my server without problems. If I try to open URL http://localhost:3000/, it just works. It displays the text "Hello World" in the browser. On line 14 you can see that / has a mapping. It renders index.html. Is this what you mean, or do you mean something else?

**Comment by rijkvanzanten** [comment]
Ahh yes I see. So it's returning your static `index.html` file, because that hits from `express.static()` I was wondering about your `res.render('index!')`. You don't have an `index.pug` file, and I was wondering if that `!` did anything 🙂
