### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by Kuckelkorn** [cmda-bt/be-course-18-19#37]
# Listing

## Name
Remco Kuckelkorn

## Repo link
[Project Tech Repository](https://github.com/Kuckelkorn/Assignment-Project-Tech)

## Summary
By setting up a server using the express package, when the server was running I created routes to the index page and the about page and a 404 error as well. The pages are based on a pug template. 
I chose for pug because I looked up comparisons and at first I choose for handlebars(express-handlebars) but because the resources on express-handlebars is a lot less compared to pug and both were a new language to me I made the decision to switch to pug. There isn't much content, because my research still isn't finished. 

### Comparisons
[NPM-compare](https://npmcompare.com/compare/ejs,handlebars,jade)
[Slant](https://www.slant.co/versus/181/185/~handlebars-js_vs_pug-jade)

## Any thoughts?
It took some more time because I wasn't at the lecture on Monday and made the assignment on Wednesday I had to figure it out more by myself and after that, I switched from handlebars to pug

**Comment by rijkvanzanten** [comment]
Heya! Good job

* You have two server.js files. I'm assuming you forgot to remove the root one when moving it into a folder
* Have you run the server to confirm if it works? I always thought you had to call `.listen()` last, but I might've been mistaken 🙂 
* Try making your readme more useful by relating it to your project. Add a description, some installation instructions on how to run your project and other relevant information.
