### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by RooyyDoe** [cmda-bt/be-course-18-19#39]
# Listing

## Name
Roy Kuijper

## Repo link
https://github.com/RooyyDoe/Project-Tech

## Summary
I tried to make the things we needed to do. Then I find out that it is really useful to use a template engine because you can make little components and just include them in another _pug_ file

## Resources used
* https://www.npmjs.com/package/pug
* https://pugjs.org/api/getting-started.html
* Tijdens de les 

## Any thoughts?
I still don't understand NodeJS javascript that good.. Is there a way that I can understand this better by reading or doing exercises. Because the learnyounode is a bit too difficult.

**Comment by rijkvanzanten** [comment]
Heya! Good job overall; couple of points:

* Focus on keeping your syntax clean. The `index.js` file is a big mess.
* I wouldn't be able to tell from your code that you're having trouble with node or servers. This is all looking pretty decent (except for the aforementioned messiness)
* There's an odd trailing `p` character. Did you try running your server? I don't think it'll run with this there

https://github.com/RooyyDoe/Project-Tech/blob/b576ac74a9f33b263764ef2efa512592d61267d7/index.js#L7

* While the check for `req.accepts("html")` works just fine, you're not checking for that anywhere else. For every other route, you're responding with HTML. Why is the 404 page different?

**Comment by RooyyDoe** [comment]
Thank you Rijk, for the feedback and looking into my work. I have changed my full notFound function and tried to only use one kind of function so my index.js is cleaner.

I heard my classmates talk about moving the functions in my index.js file into another file and then import/require them back. Should I do this or keep what I have right now?

**Comment by rijkvanzanten** [comment]
The file is still a bit messy tho ;P Try running it through [Prettier](https://prettier.io/playground/)!

> I heard my classmates talk about moving the functions in my index.js file into another file and then import/require them back. Should I do this or keep what I have right now?

Your main index.js file is only 30 or so lines long, and by cleaning it up even less. I think moving stuff out of there right now will introduce more complexity than the decrease in file size of the main index file is worth. That being said, as soon as that file gets too long to comfortably work in you should consider moving things out.

**Comment by rijkvanzanten** [comment]
And... you made a small (but crucial) mistake in this bit:

```js
app.
    use(express.static('static'))
    set('view engine', 'pug')
    use('/static', express.static('static'))
```

This should instead be

```js
app
    .use(express.static('static'))
    .set('view engine', 'pug')
    .use('/static', express.static('static'))
```

Every method needs a dot, it's the same as writing:

```js
app.use(express.static('static')).set('view engine', 'pug').use('/static', express.static('static'))
```

**Comment by RooyyDoe** [comment]
Hey Rijk, 

I was finishing my last commit when the class ended and I didn't push my last commit of the index.js file. So I think you haven't seen the last version of my index.js file. Hopefully it is a better/cleaner file.

**Comment by rijkvanzanten** [comment]
![](https://starecat.com/content/wp-content/uploads/in-case-of-fire-git-commit-git-push-leave-building.jpg)
