### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Sajjad0405** [cmda-bt/be-course-18-19#4]
# Package

## Name
`Sajjad Ali`

## Repo link
https://github.com/Sajjad0405/dating-app.git

## Summary
`Ik heb de packages.json file aangemaakt en de opdracht gemaakt zoals het volgens mij bedoeld was. Verder moet ik alleen nog packages toevoegen voor mijn job story. Verder heb ik ook een gitgnore file aangemaakt en de node_modules file daarin bijgezet.`

## Resources used
`Danny ;)`

## Any thoughts?
`De lessen zijn heel handig wanneer er een live demo wordt gegeven. Dit helpt zeer want je ziet eigenlijk hoe je een bepaald opdracht doet.  `

**Comment by rijkvanzanten** [comment]
Hey there!

* Try adding a license file to the repo so it's clearer for external developers (like me!) what the usage permissions of your code are.
* Your package.json says that the author is `root`. Where did that come from? You should change that to reflect the actual author (you! 😄 )
* You might want to add `.DS_Store` to the `.gitignore` file. Those sneaky hidden (mac) files always seem to make their way into projects 🙂 

Overall good job 👍

**Comment by dandevri** [comment]
Looking good! 🎉 

If you want you can expand your readme, giving a brief description of your project instead of just the installation instructions.

**Comment by dandevri** [comment]
Oh, and you've only used a `devDependency` (nodemon). Also, try requiring a module in your index.js file and run it with Node!
