### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by victorlaforga** [cmda-bt/be-course-18-19#40]
# Listing

## Name
`Victor Laforga`

## Repo link
[https://github.com/victorlaforga/project-tech](https://github.com/victorlaforga/project-tech)

## Summary
`I've created my own localhost that handles routes and server static files like CSS, images etc. In the beginning I didn't understand much about servers en http. And how to use express and PUG. But the more I worked with it, the better I understand it. I got a bit stuck in the morning, that's why I am a bit late  uploading my work. Sorry for that. `

## Resources used

- PUGs guide
- expressJS guide
- https://stackoverflow.com/

## Any thoughts?

Good exercise to learn more about routes en static files etc. I missed the class on monday but I think I helped myself out by doing some extra research instead.

**Comment by rijkvanzanten** [comment]
Hey @victorlaforga! Good job

* There's a typo in your `index.html` page: https://github.com/victorlaforga/project-tech/blob/master/static/index.html#L29
* Be careful with indentation and code cleanup. I noticed you use .eslint, but your `index.js` file is still a mess.
* Consider making the `port` configurable as an environment variable
* You have installed pug, but you're not using it. Or the template files are missing from the repo.
* Why are you manually constructing bits of HTML while you have pug installed as well? https://github.com/victorlaforga/project-tech/blob/master/index.js#L35
* If you're doing string concatenation, consider using the es6 backtick syntax to make your life a bit easier:

```js
// From

var doc = '<!doctype html>'

doc += '<title>' + recipes.title + ' - My recipes website</title>'
doc += '<h1>' + recipes.title + '</h1>'
doc += '<p>' + recipes.description + '</p>'

// to

var doc = `
<!doctype html>
<title>${ recipes.title }</title>
<h1>${ recipes.title }</h1>
<p>${ recipes.description }</p>`;
```

**Comment by rijkvanzanten** [comment]
Also, you might want to add a comment as to why you're doing this:

```js
while (++index < length) {
```

It's quite uncommon. Seeing that you're looping over `data` in order to generate a HTML string, consider using `.reduce()` instead

**Comment by victorlaforga** [comment]
Thnx for the feedback Rijk! I appreciate it.

**Comment by rijkvanzanten** [comment]
@victorlaforga I think you got some merge conflicts, didn't fix them, and pushed it to GitHub 😬

**Comment by rijkvanzanten** [comment]
Also, did you work together with @StefanGerrits2?

https://github.com/victorlaforga/project-tech/blob/d40f117f67df145239be23d20fbc7d3b30236375/index.js#L60-L69

https://github.com/StefanGerrits2/datingwebsite-bloktech/blob/3cd1250e31b29287103f04eb374acf97e5ed1427/index.js#L45-L60

Your way of building up the HTML is surprisingly similar. Or is there an online tutorial you both referenced?

**Comment by victorlaforga** [comment]
Yes I was having some trouble merging the files. No I didn't work with stefan, we may have some similair work because we used the slideshow from monday as a reference.
