### ISSUE TITLE
Bug section link leads to a 404 page on the week 3 page

### ISSUE THREAD

**Issue by MartijnKeesmaat** [cmda-bt/be-course-18-19#41]
```Stuck? See the Bugs section of the course readme to find a list of troubleshooting tips```

**Comment by MartijnKeesmaat** [comment]
The labels don't match the issue but can't figure out if it's possible to remove them from this issue.

**Comment by dandevri** [comment]
Thanks for the heads up!

Can you make a _pull request_ to fix this? Nice little extra assignment!

**Comment by rijkvanzanten** [comment]
Quick extra GitHub Tip™: only close issues when they're solved. An open PR is a about-to-be-fixed state 🙂 

Quick extra GitHub Tip™ #2: If you add "Closes #41" or "Fixes #41" to the description of the PR, GitHub will close the issue automagically once the PR is merged 😄
