### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [cmda-bt/be-course-18-19#44]
# Data

## Name
Rowin

## Repo link
https://github.com/Rowin206/DatingApp

## Summary
This time I added an option to register for users. After that, you can delete the user. For now, I fully focussed on the functionality and understanding how it works. So, it is not the prettiest at the moment, but it works and I understand it (thankfully :)). In the future, I want to convert it more to my dating app. That's the next step. 

## Resources used
Express server example 
https://www.youtube.com/watch?v=uXTJnIUlVAA&t=
https://www.youtube.com/watch?v=ZbtZ_79UmjI&t=
https://www.youtube.com/watch?v=_fEh1vXgn_s
https://www.youtube.com/watch?v=Oive66jrwBs&t=23s
https://www.youtube.com/watch?v=PIKrh5ofQF0&t=233s

## Any thoughts?
It was pretty hard. I think I've made it harder for myself by using routes, because of that, I get a lot of errors/problems. I lost the overview due to all linked files, but in the end: I learned a lot by solving the problems.

**Comment by rijkvanzanten** [comment]
Great work 💯 

* Your whole readme is in English, except for "Bron(nen)"
* You use plural "routes", but singular "view"
* Try to keep blocks of commented-out code out of your repo. The whole point of using Git is that you have a history of all changes. All the code you've deleted can be seen very easily by "going back in time" using git
* You're using `const` and `var` mixed, try sticking to one style
* Great repo organization! Real easy to navigate and find things 🙂

**Comment by RowinVanAmsterdam** [comment]
Ah I see! I just updated the repo with your feedback. Some code is still commented-out, but the reason is that I'm still trying to make sessions work. The old commented-out code is deleted :)
