### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by Kalemis** [cmda-bt/be-course-18-19#45]
# Data

## Name
Artemis

## Repo link
[Repository](https://github.com/Kalemis/Assignments)

## Summary
I actually started this assignment last week because I thought it was part of last weeks assignment. I couldn't make it work, the data wouldn't show on the home page. I found out what the problem was and after that it all worked!
I just don't really understand what fetch exactly does and the documentation I found did not really help me. The code does work, but only because I used the example express server from last week. I can understand what fetch probably does but I just cannot find the exact function of it. 

I found that my code was getting a little messy, so I cleaned the code up a bit and gave it more structure by putting the partials in a subfolder. 

## Resources used
[Photos](https://unsplash.com/)
[Express example](https://github.com/cmda-bt/be-course-18-19/tree/master/examples/express-server)
[Users](https://randomuser.me/)
[Fetch](https://github.github.io/fetch/)

## Any thoughts?
I really like that I can use my code from last week and that it starts to feel more and more like a dating website. I will probably start all over again for the dating app but I can use this as a basis like I used the express example as a basis for these assignments.

**Comment by RowinVanAmsterdam** [comment]
Instead of using fetch, you could use a XMLHttpRequest. I found that a little easier, but yes I want to understand fetch as well :D

**Comment by rijkvanzanten** [comment]
Looking good! 💯 

You might want to consider moving some of the routes in grouped router files. Your main index.js file is a 180 lines already and will only continue to grow after this week 🙂

**Comment by Kalemis** [comment]
Thanks! I created a separate file for the routes 👍
