### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by Sajjad0405** [cmda-bt/be-course-18-19#46]
# Data

## Name
Sajjad Ali

## Repo link
https://github.com/Sajjad0405/dating-app

## Summary
Er is deze week veel gebeurd. Ten eerste ben ik overgestapt van brackets naar vscode. Niet omdat brackets niet goed genoeg was, maar vscode ben ik begonnen te gebruiken omdat ik via de code editor ook de terminal kan gebruiken, en dit is heel handig. 
Daarnaast heb ik mijn job story geupdated en al begonnen met de week opdracht van backend en frontend.

Ook was ik eerst begonnen met de templating engine pug maar het was voor mij echt niet duidelijk hoe ik pug moest gebruiken. Bijvoorbeeld het opmaak voor html zag er anders uit en het lukte mij ook niet om javascript te schrijven binnen pug.
Daarom ben ik al toch overgestapt naar de andere templating engine, namelijk EJS. Tot nu toe vind ik EJS veel makkelijker en handiger om te gebruiken. Het toevoegen opdracht voor nu heb ik daarom ook gemaakt in de EJS templating engine. 

## Resources used
https://codeburst.io/javascript-linting-tools-comparison-ebcb4aa23c49
https://pugjs.org/api/getting-started.html
https://ejs.co/
https://www.npmjs.com/package/ejs
https://www.jslint.com/

**Comment by rijkvanzanten** [comment]
Good job! 💯 

I gotta agree on Pug vs EJS. I personally prefer EJS for exactly the reasons you mentioned 🙂 

* You have a couple of "stray" files left in your repo from (I presume) previous tests: `test.html` / `header.pug`. You might want to remove those to prevent confusion
* Same goes for in the `views` folder; you still have a template in there in `pug`
* Seeing that you're not using it anymore, consider removing Pug from `package.json` so it doesn't get installed when I install your project: https://github.com/Sajjad0405/dating-app/blob/master/package.json#L33
