### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by MartijnKeesmaat** [cmda-bt/be-course-18-19#47]
# Data

## Name
Martijn Keesmaat

## Repo link
[Repo](https://github.com/MartijnKeesmaat/dating-app)

## Summary
Added a basic version of the [ice-breaker](https://github.com/MartijnKeesmaat/dating-app) feature. I now have a form that receives data and then renders it on another page through a POST method. I also started looking at how I could implement postCSS instead of SASS(which I usually use). The cool thing about postCSS is that it enables you to pick your own packages instead of providing a set list of features as SASS does.

## Resources used
- [Node JS Tutorial for Beginners #30 - Handling POST Requests
](https://www.youtube.com/watch?v=rin7gb9kdpk)
- [Moving from SASS to PostCSS, why, what and how
](https://medium.com/@im.simonecorsi/moving-from-sass-to-postcss-why-what-and-how-f68b1bc760dc)
- [npm body parser](https://www.npmjs.com/package/body-parser)

## Any thoughts?
I liked this assignment because we had to find our own instead of just copying the examples. I tried to ignore the example code and find out how to get my feature working on my own. In the beginning, it was pretty frustrating because I couldn't seem to fix it. After staring at a 404 page for two hours I got it working. Which felt great when it did work 🌈

**Comment by rijkvanzanten** [comment]
Great job! 🥇 

Impressive wiki, really useful

You might want to rename [the `start` script in package.json](https://github.com/MartijnKeesmaat/dating-app/blob/master/package.json#L7) to `dev`, and add a "true" start script that relies on Node itself. You don't want to run the app in production using `nodemon` 🙂 

I'm a tad bit confused about the `server` folder though. Aren't most of the other files in the repo related to the server too? Why are those two files specifically in the server folder?

**Comment by MartijnKeesmaat** [comment]
@rijkvanzanten Thanks for the feedback Rijk. I wanted to separate my JS files. But now that you say it, there are indeed multiple files I could include in the server folder.  

I have created issues in my repo from your feedback:
- [Folder structure](https://github.com/MartijnKeesmaat/dating-app/issues/19)
- [npm dev script](https://github.com/MartijnKeesmaat/dating-app/issues/18)
