### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by emmaoudmaijer** [cmda-bt/be-course-18-19#48]
# Data

## Name
Emma Oudmaijer

## Repo link
https://github.com/emmaoudmaijer/datingsite

## Summary
I have tried to create a form from which you can create a small account and upload a photo

## Resources used
https://pugjs.org/api/getting-started.html 

## Any thoughts?
I thought it was a nice assignment at the beginning and thought that I would get it right. But I found it harder than I thought and I didn't quite succeed.. I don't know why it's not working. When posting the form, i don't know how to read the fields from memory on the account page.

**Comment by rijkvanzanten** [comment]
> I don't know why it's not working.

https://github.com/emmaoudmaijer/datingsite/blob/d394fbb4608ba8e50c23fe0ed7afcce4986b00c5/server/server.js#L72-L75

It actually looks like you forgot to change the name of the function

```js
app.get('/account', account)
function aanmelden(req, res) {
        res.render('account.pug', {data:account});
}
```

I'm not sure if it's the exact cause of your problem, but it will definitely screw something (else) up

Also, just like last week, there are still a couple confusing things going on in your repo. You have an `index.js` with seemingly random tests, a `server.js` file that is duplicated in the `server` folder, and a `dating-website` folder that looks like a previous test of what now became `static`. 

Consider programming in English. Seeing that JavaScript itself is English ("function" "variable" "while") it's easier to read if the names are in English as well (it also makes it easier for non-dutch programmers to go through your code).

**Comment by emmaoudmaijer** [comment]
okay thanks, I'm going to try that! My repo is clearly a mess,  but I'm going to organize that this week
