### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by StefanGerrits2** [cmda-bt/be-course-18-19#49]
# Data

## Name
`Stefan Gerrits`

## Repo link
[Repo](https://github.com/StefanGerrits2/datingwebsite-bloktech)

## Summary
I tried to make the user submit a form so the data he enters will show up on his profile. However I did not succeed in this. I can't figure out how to render data with pug. For example I even tried to set up some fake data in `var data` in my index.js and tried rendering this in my list.pug file with `script. 
     p #{data}` and many more different options till it worked, but no luck. I also couldn't manage the data the user puts in, in the form, will actually push into the data variable.

## Resources used
https://pugjs.org/api/getting-started.html
[Slides lecture 3](https://docs.google.com/presentation/d/137YTmMadaUNCJ2ksKHzU_NCZT-BIv3q9tGhXc38EZ3g/edit#slide=id.g32a104bd4c_0_47)
https://github.com/cmda-bt/be-course-18-19/blob/master/examples/express-server/index.js

## Any thoughts?
I will probably change from pug to ejs if I can't fix this issue. I think this assignment was pretty hard and I hope I can fix this issue soon so I don't fall behind.

**Comment by StefanGerrits2** [comment]
I have fixed the problem with fake data rendering! I changed some code which you can see in my commits. Now I can render fake data from index.js to a pug file.

I still have problems pushing the data entered in the form into the data array so I can render it in pug. Hopefully I can figure this out soon.

EDIT: I fixed it!

**Comment by rijkvanzanten** [comment]
I love these follow up issues 😂 

Good job 🙂 

* Consider programming in English. Makes it easier to read (seeing that the languages we use are in English too), and it makes it easier for English speaking devs to go through your code.
* You might want to look into extracting your router functions into separate files. Your main index file will grow beyond belief once you start adding database manipulation!
* Your JavaScript contains quite a few code style issues (mixed tabs / spaces, single vs double quotes, semi-colons vs no semi-colons). It's crucial to keep your code tidy. Without, it will get incredibly difficult to find bugs later on. Try ~installing a ~ using your linter if you want to be warned of these types of issues
* I think you left some old files in the `static` file (all the HTML files)

**Comment by StefanGerrits2** [comment]
Thanks for your feedback,

> Consider programming in English. Makes it easier to read (seeing that the languages we use are in English too), and it makes it easier for English speaking devs to go through your code.

Do you mean the website language? or names for variables, functions etc?

> You might want to look into extracting your router functions into separate files. Your main index file will grow beyond belief once you start adding database manipulation!

I will work on this :)

> Your JavaScript contains quite a few code style issues (mixed tabs / spaces, single vs double quotes, semi-colons vs no semi-colons). It's crucial to keep your code tidy. Without, it will get incredibly difficult to find bugs later on. Try ~installing a ~ using your linter if you want to be warned of these types of issues

I've added some new rules for my ESLint. This should fix these kind of issues!

> I think you left some old files in the static file (all the HTML files)

You're right, these were some test files. I deleted them :)

**Comment by rijkvanzanten** [comment]
> Do you mean the website language? or names for variables, functions etc?

The latter! It wordt quite verwarrend when je languages combineren.
