### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by cenikk** [cmda-bt/be-course-18-19#5]
# Package

## Name
Kaan Cenik

## Repo link
https://github.com/cenikk/datingapp

## Summary
`I took my first few steps in making a package.json and learned how to add and require modules.
I learned how devDependencies works and how you add your own script to make it run.`

## Resources used
https://docs.npmjs.com/files/package.json  
https://nodesource.com/blog/eleven-npm-tricks-that-will-knock-your-wombat-socks-off/

## Any thoughts?
This first lesson was difficult to progress at first but once exercising with it, it got pretty clear and I understand everything way better now. I even managed to help a few classmates out, which helped me even more in understanding how everything works.

**Comment by rijkvanzanten** [comment]
Heya! Well done 😄 

* You might want to add `.DS_Store` to the `.gitignore` file to make sure those sneaky files don't make it into the repo
* The license in your repo is different from the one referenced in `package.json` (MIT vs ISC)
* Good job on the dev vs regular dependencies 🙂

**Comment by dandevri** [comment]
Good job on helping other students in your class!
