### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by Plous01** [cmda-bt/be-course-18-19#50]
# Data

## Name
Paulien

## Repo link
[My repository](https://github.com/Plous01/ProjectTech)

## Summary
Before I started this assignment, I watched some tutorials on youtube and experimented with my code. I also decided to change my job story after some struggles. Because of the struggles (and lots of errors), my code looks (a bit) messy, so I am going to clean it this week! 

I made it possible for users to register. They can fill in the form and click on the button. After signing up, you can see a (very basic) list of people that submitted (if you don't see it, you can add `/persons` in the URL to see a list of all the persons). When you click on a person, you can see the details about that person.

I have made two basic responsive HTML files (register and the homepage of the dating website) and added some CSS, which I am going to improve this week.   

## Resources used
* The coding train (youtube);
* Stackoverflow
* MDN web docs

## Any thoughts?
Personally, I thought this assignment was hard. I had to Google a lot to get my code to work because I didn't understand it and I lost the overview. Therefore, there is still a lot of work to be done.

**Comment by rijkvanzanten** [comment]
Hey there! Good job 👍 

You've already mentioned that your code is a bit messy, so I won't reiterate that.

Also clean up the repo itself when you're going through your code! There's a stray `index.html` page, and I believe the `CSS` and `Afbeeldingen` folders should be in `public` (or not in the repo to begin with) (also make them lowercase)

Quick other tip: rename `person.js` to `database.js` or `person-database.js`. The file exports a database, not a person 🙂
