### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by Sanderoost** [cmda-bt/be-course-18-19#51]
# Data

## Name
Sander Oostenbrink

## Repo link
https://github.com/Sanderoost/blok-tech

## Summary
I created a form in pug that lets the user fill in a film or serie.
When enter is pressed, the data adds to the array and is saved.

## Resources used
Powerpoint slides week 3
Stackoverflow
Pug forum

## Any thoughts?
For some reason i can only delete the first film/serie in the list... i think it has something to do with the for loop.
Pug is still a little difficult sometimes.

**Comment by rijkvanzanten** [comment]
Good job 💯 

* What does a `.sublime-workspace` file do? I'm a sublime user myself but never encountered one 🙈
* Pug can be hard to understand sometimes. If it's holding you back, consider moving to EJS or another alternative that's a little bit easier to understand
* You have some code style inconsistencies (double vs single quotes, semi-colons vs no semi-colons). Use a linter to point you to these issues
* Consider moving your route functions into separate files. Once you get a database involved, these functions will grow exponentially in size, making the whole file harder to read
