### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by markschuttehva** [cmda-bt/be-course-18-19#54]
# Data

## Name
Mark Schutte

## Repo link
https://github.com/markschuttehva/Techproject

## Summary
I made a pug file that shows the data from the array saved in the database.
I want to display the saved files in my database (name, location, age etc. ).

## Resources used
- Thijs Spijker, Student in my class
- https://pugjs.org/api/getting-started.html
- https://pugjs.org/language/code.html
- https://html2jade.org/
- https://github.com/pugjs
- https://pugjs.org/api/reference.html

## Any thoughts?
Pug is not easy to use (for me), but somehow I managed to show the data in a file. This was quite exciting for me to be honest. Pug is not easy but I hope I'll manage working with it. Thankfully Thijs Spijker was there to help me with this.

**Comment by rijkvanzanten** [comment]
Good job 💯 

If Pug is holding you back, consider looking into alternatives. You're in a stage of the project where you still have the chance to port over your view templates. Once your app gets more and more pages, it'll get harder and harder to switch templating engine.

* Remove [commented out codeblocks](https://github.com/markschuttehva/Techproject/blob/master/index.js#L32-L34) from your code. This is what Git is for (you can rollback at any time to see what you deleted)
* You're trying to render two pages at the same time: https://github.com/markschuttehva/Techproject/blob/master/index.js#L43-L44. This won't work
* Why did you put just the data in the server folder? Aren't the other things server related as well?

**Comment by markschuttehva** [comment]
Dear Rijk,

Thanks for the feedback :blush:

I will keep trying to get into pug, it isn't easy but sounds challenging to me.
I indeed was trying to render two pages at the same time and I was wondering why it would not work, I fixed it in my last update.
