### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by cenikk** [cmda-bt/be-course-18-19#55]
# Data

## Name
Kaan Cenik

## Repo link
https://github.com/cenikk/datingapp

## Summary
I've updated my whole dating-app into making a user able to register and when he does, his data is (for now only server-side) being stored in an Array. After he logs in, he can see his data and for now, it's also possible to delete this. 

## Resources used
To help me adding and removing a user: [Slides-3](https://docs.google.com/presentation/d/137YTmMadaUNCJ2ksKHzU_NCZT-BIv3q9tGhXc38EZ3g/edit#slide=id.g4e3b0a74b9_1_1236)
To find out how "body-parser" exactly works: [npmjs/body-parser](https://www.npmjs.com/package/body-parser)  
To find out how "slugify" exactly works: [npmjs/slugify](https://www.npmjs.com/package/slugify)

## Any thoughts?
I feel like this week I've not made enough progress in my dating app and that I'm now a bit behind on everything. Since next week is kinda our last week before the oral exams, I still feel like a lot needs to be done to get my dating app the way I want it. So it's gonna have to be a few hard working hours for me since next week we're going to be focussing on storing data into a database, and something tells me it's not going to be very easy.

**Comment by rijkvanzanten** [comment]
Good job 💯 

> and something tells me it's not going to be very easy.

👀 

* If you go with the MVC pattern, try also extracting your routes into separate controllers too

**Comment by cenikk** [comment]
Yes, you're right, would make my code a lot more readable as well. Thanks!
