### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by victorlaforga** [cmda-bt/be-course-18-19#56]
# Data

## Name
Victor Laforga

## Repo link
[https://github.com/victorlaforga](https://github.com/victorlaforga)

## Summary
This week I started working with pug. I found it hard because of the pug language, it quite different then html or ejs. I was doubting to change the templating engine to ejs, just because I find it hard to work with. But on the other hand, it's also a good challenge for myself to get to understand pug much better.

The positive thing is that I can now upload own made recipes and see them. I still can't delete them becauses I was struggling with that. But I will be working on that.

EDIT: **I switched to ejs, instead of using pug.**

## Resources used
[https://pugjs.org/language/includes.html](https://pugjs.org/language/includes.html)
[https://www.youtube.com/watch?v=kt3cEjjkCZA](https://www.youtube.com/watch?v=kt3cEjjkCZA)
[https://www.npmjs.com/package/find](https://www.npmjs.com/package/find)
[https://www.freecodecamp.org/forum/t/whats-the-best-view-engine-for-node-js-ejs-jade-or-handlebars/76192](https://www.freecodecamp.org/forum/t/whats-the-best-view-engine-for-node-js-ejs-jade-or-handlebars/76192)

## Any thoughts?
It was a difficult exercise with some obstacles, but I'm happy I got it to work.

**Comment by rijkvanzanten** [comment]
@victorlaforga trying Pug

![](https://media.giphy.com/media/wYyTHMm50f4Dm/giphy.gif)

* You shared your full GitHub profile. Subtle flex? 
* Good job overall 👍 
* Make your readme useful, I know how to install nodemon. I want to know what your project is, how I use it, etc

**Comment by victorlaforga** [comment]
@rijkvanzanten Haha no 😆,  I just added some project's I've made in my first and second year to show it to my internship. Yeah I will work on the readme these days, thnx! 

I have one question though, I can't get the remove button to work. Any idea what the problem could be?
