### ISSUE TITLE
Data (Feature)

### ISSUE THREAD

**Issue by GiovanniDw** [cmda-bt/be-course-18-19#58]
# Data

## Repo link

[GiovanniDw/pt-course](https://github.com/GiovanniDw/pt-course)

## Summary

Had a lot of issues with the movie example, tried to apply it with listing games, but a little different. had a lot of issues, trying to fix all in this weekend

## Resources used

- ejs.co
- [stackoverflow cannot-read-property-title-of-undefined-express](https://stackoverflow.com/questions/20411459/cannot-read-property-title-of-undefined-express)
- [stackoverflow how to pass array to ejs](https://stackoverflow.com/questions/24592760/how-can-i-pass-an-array-to-an-ejs-template-in-express)
- [npm array-find](https://www.npmjs.com/package/array-find)

**Comment by rijkvanzanten** [comment]
Hey there!

* Your code is a bit of a mess. Please use a linter, or run it through Prettier or something similar before uploading it to GitHub.
* You're importing a bunch of packages that you're seemingly not using
* Why are you requesting Google once and not doing anything with it?

> trying to fix all in this weekend

Try fixing it _before_ the deadline next time 😁
