### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by iamDistractech** [cmda-bt/be-course-18-19#6]
# Package

## Name
Thijs Spijker

## Repo link
https://github.com/iSirThijs/pt-tech/

## Summary
I completed the assignment, created a package.json file and added a .gitignore, license and README.md

## Resources used
Prior knowledge
Github License chooser

**Comment by rijkvanzanten** [comment]
Good job!

Try adding a module to your JS file to see if dependency installation is working 🙂 

![](https://media.giphy.com/media/3oEduV4SOS9mmmIOkw/giphy.gif)

**Comment by dandevri** [comment]
Additionally you can: 
* Look into other configs and linters
* Use more features of git or GitHub such as consistent comment messages, contributing guidelines, licenses etc.
* Expand on your `readme.md`, currently it doesn't include the instructions to install your project locally. Have a look at [The Art of Readme's](https://github.com/noffle/art-of-readme).
* Look into `lock` files. What does the `package-lock.json` do?
