### ISSUE TITLE
Storage (Feature)

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [cmda-bt/be-course-18-19#61]
# Storage

## Name
Rowin

## Repo link
https://github.com/Rowin206/DatingApp

## Summary
I did add a Mongo database. The data will not longer saved in a local json file, but in a database. Unfortunately, the sessions itself are not working yet. Still busy with it. The MongoDB itself is still local, the next step is to upload it to a service.

## Resources used
MongoDB server example 
https://zellwk.com/blog/crud-express-mongodb/
https://www.youtube.com/watch?v=pWbMrx5rVBE&t=54s
https://www.youtube.com/watch?v=cOt8LfcA9wY&t=302s

## Any thoughts?
I think it was a very nice move to let us start with placing data in a local json file. So it was very clear when we had to transfer it to a database. To be honest, I think the sessions are one step too much. I was already happy that the database was working hehe. Hopefully the sessions will work too soon :P.

**Comment by rijkvanzanten** [comment]
Heya! Good job

By the looks of it, you're trying to initialize the sessions per route. This will result in different sessions for the different routes while you actually want to have a single session for your whole app. Moving https://github.com/Rowin206/DatingApp/blob/master/route/login.js#L21-L27 to `index.js` might already solve a lot of your problems 🙂 

The same goes for the database. You're initializing a new database connection for every route file. Instead, you can initialize the database connection in a separate `database.js` file, and require that into your separate routes. That way you're reusing the same database connection across routes.

**Comment by rijkvanzanten** [comment]
Also, if you're up for an extra challenge, look into ways to encrypt the password before saving it to the database (like bcrypt) 🙂
