### ISSUE TITLE
Storage (Feature)

### ISSUE THREAD

**Issue by nlvo** [cmda-bt/be-course-18-19#62]
# Storage

## Name
Lien Vo

## Repo link
[Dating app](https://github.com/nlvo/dating-app)

## Summary
Sketch a database structure. Setup a local mongodb to store data. Next step will be sessions and using a service like Heroku or something similar.

## Resources used

1. [Lecture 4 slides](https://docs.google.com/presentation/d/1kN7TLs3_wbZykrM0BK7mQlofaXXSOq-BgsqsugUgh7Q/edit#slide=id.g33c7310eb9_0_521)
2. [Docs | mongodb](https://docs.mongodb.com/)
3. [Example database schema design](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-1)

## Any thoughts?
Setting up a local database was doable and setting up the structure, but still working on the sessions.

**Comment by rijkvanzanten** [comment]
Good job 💯 This is all looking pretty good. One tip I have is to split up the routes of your app into separate files, to keep your main index.js file smaller and easier to read.
