### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by LarsBreuren** [cmda-bt/be-course-18-19#68]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Lars`

## Class
`206 / Tech4`

## About me
`I'm Lars, CMD student. Passionated about Front-end and improving websites in terms of 
development and UX. I love making websites with the latest features & great UX. `

## Goals
`I'm hoping to learn about the back end. I know HTML & CSS but not as much as i want about JS & PHP. I really would like to know how to set up a database and hook it up to a website.`

## Skill level
`HTML & CSS: Intermediate.
JS: Begineer.`

## GitHub username
`https://github.com/LarsBreuren`

## GitHub repository
`https://github.com/LarsBreuren/BlokTech`

**Comment by dandevri** [comment]
👋 Hi Lars, the link is added to the admin sheet.
