### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by TheKevSter35** [cmda-bt/be-course-18-19#69]
### My Introduction
Kevin - CMD student from Amsterdam

### Name
Kevin Curi

### Class
Tech 4

### About me
My name is Kevin. I'm 24 years old and i'm from Amsterdam. I just finished my intership @ Bikkelhart and in mei i'm going to work there. Also i like to play videogames in free time.

### Goals
My goals: That i have more knowledge with JS en can create nice stuff with it/

### Skill level
My skill level would be intermediate. I know the basics

### GitHub username
`TheKevSter-NL
https://github.com/TheKevSter-NL

### GitHub repository
https://github.com/TheKevSter-NL/be-course.git

**Comment by dandevri** [comment]
👋 Hi Kevin, the link is added to the admin sheet.
