### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by emmaoudmaijer** [cmda-bt/be-course-18-19#7]
# Package

## Name
Emma Oudmaijer

## Repo link
https://github.com/emmaoudmaijer/datingsite 

## Summary
I searched for packages for my dating site and tried to install them. I started working with node.js.

## Resources used
https://www.npmjs.com 

## Any thoughts?
I didn't know how to start with the exercise and it was difficult at the beginning, but if you finally get it, it's fun.

**Comment by rijkvanzanten** [comment]
Hey emma!

Good job 🙂 

Couple of points:
* You might want to add `.DS_Store` to `.gitignore` so those annoying mac files don't end up in your repo
* Consider moving the files from the application into it's own folder so it's a bit easier to see what's going on in the repo
* The license in your `package.json` file is different from the one in the repo
* Try splitting up the front end code from the back-end logic. Especially seeing that it's both JavaScript (is `index.js` server or client?)

**Comment by dandevri** [comment]
Looking good! 🎉 

Indeed, what @rijkvanzanten is saying: try to make a clear distinction on which code is server-side or client-side by moving files in folders. Pay attention to the way you name your files.
