### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by TomWesterhof** [cmda-bt/be-course-18-19#70]
# My Introduction

## Name
Tom Westerhof

## Class
VID 2

## About me
CMD-student die op dit moment de minor Visual Interface Design volgt

## Goals
Meer te weten komen over webanimaties :)

## Skill level
Ik heb het idee dat ik al aardig wat weet van HTML/CSS, maar dat komt vooral omdat ik het leuk vind om dingen uit te proberen en uit te zoeken

## GitHub username
TomWesterhof

## GitHub repository
https://github.com/TomWesterhof/webanimaties

**Comment by dandevri** [comment]
Whoops! Wrong link, can you re-create this issue in this repository? Thanks 🎉 

https://github.com/cmda-minor-vid/web-animation-18-19/issues/new/choose
