### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by lennartdeknikker** [cmda-bt/be-course-18-19#71]
# My Introduction

I'm Lennart de Knikker, I'm a regular second year CMD student, excited to learn more about nodeJS, MongoDB, Express, Angular and other frameworks like that. 

## Name
Lennart de Knikker

## Class
212

## About me
I'm Lennart de Knikker, I'm a regular second year CMD student, excited to learn more about nodeJS, MongoDB, Express, Angular and other frameworks like that. 

## Goals
After this class, I want to be able to actually build a complete web application, instead of just parts of it.

## Skill level
Intermediate

## GitHub username
https://github.com/lennartdeknikker

## GitHub repository
https://github.com/lennartdeknikker/be-course

**Comment by dandevri** [comment]
👋 Hi Lennart, the link is added to the admin sheet.
