### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by mouringh** [cmda-bt/be-course-18-19#72]
# My Introduction

## Name
Mouringh van der Veen

## Class
VID_2

## About me
Visual Interface Design student 

## Goals
Create beautiful and meaningful UI designs to improve the world, a little bit 

## Skill level
intermediate

## GitHub username
https://github.com/mouringh

## GitHub repository
https://github.com/mouringh/VID2_HTML_CSS.git

**Comment by dandevri** [comment]
Whoops! Wrong link, can you re-create this issue in this repository? Thanks 🎉 

https://github.com/cmda-minor-vid/web-animation-18-19/issues/new/choose
