### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by AngelaMastenbroek** [cmda-bt/be-course-18-19#74]
# My Introduction

## Name
Angela Mastenbroek

## Class
VID2

## About me
3e jaars CMD student die werken met HTML, CSS en vooral JS erg moeilijk vind

## Goals
Basis kennis van coderen beter leren begrijpen en (kleine) animaties kunnen coderen

## Skill level
Beginner

## GitHub username
https://github.com/Mastena001

## GitHub repository
https://github.com/Mastena001/Web-Animation

**Comment by dandevri** [comment]
Whoops! Wrong link, can you re-create this issue in this repository? Thanks 🎉 

https://github.com/cmda-minor-vid/web-animation-18-19/issues/new/choose
