### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Coenmathijssen** [cmda-bt/be-course-18-19#75]
# Package

## Name
Coen Mathijssen

## Class
Blok Tech 4

## Repo link
https://github.com/Coenmathijssen/NPM-boilerplate

## Summary
Created a boiler template and a function ready for uploading to NPM

## Resources used
Youtube, Google, Github, Stackoverflow

## Any thoughts?
I found the explanation very vague, but after a bit of Googling I found out how it worked. Don't know if I did it right tough.

**Comment by rijkvanzanten** [comment]
Good job 👍 Make sure to add a `.gitignore` file though. We don't want to have a copy of all the node modules in your repo.
