### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by charder001** [cmda-bt/be-course-18-19#76]
# Package

## Name
Rick Chardet

## Class
Tech3

## Repo link
https://github.com/charder001/Project-Tech

## Summary
Created a boilerplate, generated a package.json file, installed dependencies, wrote a readme and added a license.

## Resources used
Stackoverflow, npm documentation

## Any thoughts?
Could've used a little more guidence with what should be included in a boilerplate. Don't know if i completed the exercise correctly.

**Comment by rijkvanzanten** [comment]
This is looking pretty decent 👍 

It's very common to put the `package.json` file in the root of your repo / project. Also make sure to add a `.gitignore` file to make sure you don't end up with all the node_modules in your repo.

Also, what made you pick the AGLP-3.0 license for the repo? (Btw you have a different license listed [in your package.json file](https://github.com/charder001/Project-Tech/blob/master/boilerplate/package.json#L10))
