### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Mokerstier** [cmda-bt/be-course-18-19#77]
# Package

## Name
`Wouter van der Heijde`

## Class
`TECH-4`

## Repo link
[Package-repo](https://github.com/Mokerstier/Package-boilerplate)

## Summary
Just spammed some commands `npm install camelcase` in the terminal really fun, had some difficulties with the `sudo` command because the npm packages would be installed globally that way 😢.  Eventually i figured it out so yay! 😄 

## Resources used
I used the interwebs  and the [slides](https://docs.google.com/presentation/d/1k7m98hB0hct_kL6fb7g5IbxI_YZqdPMmZApbAn8qYTo/edit#slide=id.g4ba93d3df0_1_1455) from the lecture for research about npm and eventually I started `package.json` through `npm init` command

## Any thoughts?
I simply had no idea how to start but when I looked back upon the slides `107 - 117` it all started to make sense. [This are the slides where I figured it out](https://docs.google.com/presentation/d/1k7m98hB0hct_kL6fb7g5IbxI_YZqdPMmZApbAn8qYTo/edit#slide=id.g4ba93d3df0_1_1455)
Maybe you can send people there, when they encounter some difficulties on how to start.

**Comment by rijkvanzanten** [comment]
Good job 💯 

keep an eye on the indentation and code "cleanliness" in your files. You won't have any problems yet, but funky indentation like in [the server.js file](https://github.com/Mokerstier/SumMeet-datingApp/blob/master/server.js) can make it very hard to debug issues later on. You could take a look at [Prettier.io](https://prettier.io) to automate this for you.

Regularly speaking, starting the application in NPM scripts is called `start`, not `build`. Oftentimes, `build` is being used to compile your `src` files into production ready application front-end files. You don't have any of that (yet).
