### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by SqueezyDough** [cmda-bt/be-course-18-19#78]
# Package

## Name
Leroy van Biljouw

## Class
TECH 4

## Repo link
https://github.com/SqueezyDough/Project-Tech 

## Summary
Added new dependency to package.json 

## Resources used
Homework week 1 assignments, nodemon documentation

## Any thoughts?
ez

**Comment by rijkvanzanten** [comment]
gg ez wtg ftw gtg ttyl
