### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by Wiebsonice** [cmda-bt/be-course-18-19#79]
# Package

## Name
Wiebe Kremer

## Class
Tech 4

## Repo link
[GalleryMatch - Dating site](https://github.com/Wiebsonice/GalleryMatch)

## Summary

- I created the .gitignore file to exlude some of the files wich i didnt need on git.
- I added 2 packages, the camelcase and i had the scss one working. After a discussion with Danny i decided to get rid of that one.
- After I added the 2 dependencies, i looked at DevDependencies, i installed nodemon. But im yet to get it working. And to fully understand it.
- Included the license
- Added the readme

- I've encounterd an issue with Requiring and, I am going to ask that during the next lession.

## Resources used
Mostly github, and npm pages. Also had some help from a classmate with the scss package before I deleated it.

## Any thoughts?
You showed us how to instal camelcase, wich was quite easy, but maybe show us next time how to work with the more complicated npm packages such as nodemon.

**Comment by rijkvanzanten** [comment]
Good start 👍 

* Add `.DS_Store` to your `.gitignore` file so these macOS specific files don't end up in your repo
* Try to make a clear split between the front-end and back-end files. Right now the `js` folder in `/website` is for the back-end stuff, but it's right next to the `css` folder, which might cause conflicts and confusion as soon as you start adding JavaScript files for the front-end of the website
