### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by RooyyDoe** [cmda-bt/be-course-18-19#8]
# Package

## Name
`Roy Kuijper`

## Repo link
`https://github.com/RooyyDoe/Project-Tech`

## Summary
`I made my map structure for this project and installed the nodemon package. Also, I have added a .gitignore file for this project. All this is documented in the README.md file`

## Resources used
* [Nodemon](https://www.npmjs.com/package/nodemon)
 * [Node](https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/)

## Any thoughts?
`At this moment I don't know if I can go through with the making of my project. because of the research/jobstories`

**Comment by rijkvanzanten** [comment]
Hey @RooyyDoe! Good job 🙂 

Couple of points: 

* Why is the JS in a folder prepended by an underscore? Normally that shows that an asset is internal / hidden / not supposed to be used
* Consider adding `.DS_Store` to the `.gitignore` file so it doesn't get added accidentally
* The license in the repo is different from the one mentioned in `package.json`
* The `Clone the repository` step in the readme isn't correct. You should replace it with `git clone https://github.com/RooyyDoe/Project-Tech.git`
* `npm nodemonStart` is not a valid `npm` command (unfortunately!)

**Comment by dandevri** [comment]
Also, try requiring a module in your index.js file and run it with Node! A dependency you are actually going to use in your application instead of just a `devDep`.
