### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by GiovanniKaaijk** [cmda-bt/be-course-18-19#80]
# Package

## Name
Giovanni Kaaijk

## Class
Tech 4

## Repo link
https://github.com/GiovanniKaaijk/p-Tech

## Summary

- I added the package Nodemon
- I added a script to run Nodemon
- I made a readme + license
- I made an .gitignore file to filter files from uploading to git.

## Resources used
Nodemon

## Any thoughts?
I find the homework useful, i learned about npm and how to use it. I also learned how to use Git in the terminal.

**Comment by rijkvanzanten** [comment]
Good start 👍 

* Keep in mind that there's a split between front-end and back-end code in your repo. Right now the `js` folder is right next to a `sass` folder, indicating that it's both front-end code. However, in your package.json file you're pointing nodemon to the `js` folder.
* Finish up the package.json file. Currently the description, author, and license fields are empty/wrong
