### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by martijnvdwoude** [cmda-bt/be-course-18-19#82]
# Package

## Name
Martijn van der Woude

## Class
4

## Repo link
https://github.com/martijnvdwoude/project-tech-backend

## Summary
- Initalized the Node project
- Added a package.json with dependencies and scripts
- Added sources like index.js

**Comment by rijkvanzanten** [comment]
Perfect. The one tiny nitpick I have is that the license field in the package.json file is different from the license used in the repo itself.
