### ISSUE TITLE
Listing (Feature)

### ISSUE THREAD

**Issue by martijnvdwoude** [cmda-bt/be-course-18-19#83]
# Listing

## Name
Martijn van der Woude

## Class
4

## Repo link
https://github.com/martijnvdwoude/project-tech-backend

## Summary
- Added .gitignore file
- Written basic README
- Implemented .env environment variable configuration
- Implemented template engine (Pug)
- Added some routes for `/login` and `/index`
- Added 404 response for `/`
- Added nodemon as dev dependency

## Resources used
- Node documentation
- Nodemon documentation
- Express documentation
- Pug documentation

**Comment by rijkvanzanten** [comment]
While it is a matter of personal preference, you could consider chaining the `app` method calls to shorten the file a little bit:

before

```js
// parse application/json
app.use(bodyParser.json())

// Use Pug as view engine
app.set('view engine', 'pug')

// Serve static files from public
app.use(express.static('public'))

// Define routes
app.get('/index', (req, res) => {
    res.render('index', { title: 'Hey', message: 'Hello there!' })
})
```

after

```js
app
  .use(bodyParser.json()) // parse application/json
  .set('view engine', 'pug') // Use Pug as view engine
  .use(express.static('public')) // Serve static files from public
  .get('/index', (req, res) => {
    res.render('index', { title: 'Hey', message: 'Hello there!' })
  })
```
