### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by rico1136** [cmda-bt/be-course-18-19#84]
# Package

## Name
Rico Zethof

## Class
Tech 4 

## Repo link
https://github.com/rico1136/-friendsAndFoes

## Summary
Nodemon geinstalleerd
Hello world express geinstalleerd

## Resources used
Npm website

**Comment by rijkvanzanten** [comment]
Good job. You could consider the file structure a little bit. Right now there are some assets in a (capitalized) `Wiki` folder that aren't directly related to the application's source code intermingled with the app itself. You could move the app source code into a dedicated `src` folder. Also consider where you would put the front-end javascript vs the back-end javascript. Having a `server.js` file right next to a (client side) `js` folder (in the future) might be very confusing
