### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by kylebot0** [cmda-bt/be-course-18-19#85]
# Package

## Name
Express server

## Class
TECH 4

## Repo link
https://github.com/kylebot0/Package-BE/tree/Backend

## Summary
Een simpele server aangemaakt met de package van express. De server doet op dit moment nog niks, omdat er geen html bestanden zijn toegevoegd.

## Resources used
Nodemon en Express.Js

## Any thoughts?
De devDependecies waren redelijk lastig, maar eenmaal uitgelegd in de les niet meer.

**Comment by rijkvanzanten** [comment]
Good job.

You might want to rename the capitalized `Index.js` file to lowercase, just to make sure you don't run into any easy-to-prevent issues later
