### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by bazottie** [cmda-bt/be-course-18-19#86]
# Package

## Name
[Bas de Greeuw](https://github.com/aaraar/)

## Class
Tech-4

## Repo link
[Alchemistry](https://github.com/aaraar/alchemistry)

## Summary
- Set up development environment using a boilerplate containing Gulp, webpack and browsersync
- Deleted the entire environment and set up a complete webpack development environment using online tutorials
- Added readme and license
- Added gitignore in multiple folders to sanitize commits

## Resources used
- [First attempt](https://github.com/IamManchanda/gulp-webpack)
- [Webpack tutorial](https://hackernoon.com/lets-start-with-webpack-4-91a0f1dba02e)

## Any thoughts?
notrly

**Comment by rijkvanzanten** [comment]
> Gulp, webpack and browsersync

All at the same time? Why not just Webpack plus it's dev auto reload? Also, I don't see any of the gulp stuff in the devDependencies. Did you end up using this combo?

* I would personally keep the `dist` folder out of the repo, as it's not directly related to the progression of the development of the application (it adds clutter to the git commit history)
* I think this is a typo / tiny mistake: https://github.com/aaraar/alchemistry/blob/master/server/server.js#L10
* Are you going to build the front-end as a SPA that connects to your back-end over an API? If not, do consider how your webpack setup will work together with templating in EJS / Pug / etc when it has to be dynamically put together by the server.

**Comment by bazottie** [comment]
As mentioned I wiped the first setup because I also found it unnecessary and eventually just stuck with webpack
