### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by marissaverdonck** [cmda-bt/be-course-18-19#87]
# My Introduction

## Name
Marissa Verdonck

## Class
Tech 4

## About me
Ik word ontzettend blij van skiën! Maar ook als ik een code schrijf die werkt.

## Goals
Beter worden in Javascript en werken met data.

## Skill level
Beginner

## GitHub username
[Marissa Verdonck](https://github.com/marissaverdonck/BlokTech_DatingApp)

## GitHub repository
[Marissa Verdonck](https://github.com/marissaverdonck/BlokTech_DatingApp)

**Comment by rijkvanzanten** [comment]
👋
