### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by marissaverdonck** [cmda-bt/be-course-18-19#88]
# Package

## Name
Marissa Verdonck

## Class
Tech 4

## Repo link
[DatingApp](https://github.com/marissaverdonck/BlokTech_DatingApp)

## Summary
- working with Node
- Install packages
- Making a boilerplate
- Making a package.json file
- Difference between dependencies and devDependencies

## Resources used
- Slides from the lecture and lab
- [NPM](https://www.npmjs.com/package/nodemonl)
- [Gitignore](https://help.github.com/en/articles/ignoring-files)
- [Package.json](https://docs.npmjs.com/files/package.json)

## Any thoughts?
Er moest een boilerplate gemaakt worden maar ik had geen idee wat dat was of hoe ik het voor me moest zien. Ik ben wel aan de gang gegaan maar wist eigenlijk niet waar ik nou precies mee bezig was. Gelukkig kreeg ik van Danny wat extra uitleg in de les zodat ik het nu begrijp. 
.gitignore werkt niet en ik snap niet zo goed waarom.

**Comment by rijkvanzanten** [comment]
> Er moest een boilerplate gemaakt worden maar ik had geen idee wat dat was of hoe ik het voor me moest zien.

A boilerplate is something that can be reused in new contexts or apps without having to change it significantly. In this case, the assignment was to setup a "fresh" Node application that could act as a boilerplate (starting point) for future applications, like the dating app you're about to build.

> .gitignore werkt niet en ik snap niet zo goed waarom.

You most likely commited the `node_modules` _before_ you added the `.gitignore` file. From now on, any changes in `node_modules` are ignored, but the original files are still there. You can try following these steps to clean it up: http://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/

(Also add `.DS_Store` to your gitignore file while you're at it)
