### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by victorlaforga** [cmda-bt/be-course-18-19#9]
# Package

## Name
`Victor Laforga`

## Repo link
[https://github.com/victorlaforga/project-tech](https://github.com/victorlaforga/project-tech)

## Summary
`I started working with node.js and installed 3 packages, I also uninstalled one package. I made a license and a gitignore file.`

## Resources used

- Github
- [https://www.npmjs.com/](https://www.npmjs.com/)

## Any thoughts?
`I still find it hard to choose packages that apply to my job story. I still have no job story chosen because I am still searching what is achievable to build, but I do have 5 job stories which I can choose from. `

**Comment by rijkvanzanten** [comment]
Hey Victor! Nice work.

Couple of points: 
* Consider adding `.DS_Store` to the `.gitignore` file so it doesn't sneak in the repo later
* You can install nodemon as a local devDependency of your project. This results in there being less install steps for the user (only npm install). 
* ~Nodeom~ → Nodemon
* Why did you copy and paste a piece of the Lodash docs into your readme? Doesn't seem relevant to your project to me.
