### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by joanpadolina** [cmda-bt/be-course-18-19#91]
# Package

## Name
Joan Padolina

## Class
Tech-4

## Repo link
[Package install ](https://github.com/joanpadolina/Project_Tech)

## Summary
This week I've learned to install packages like express and camelcase. After a while I learned how to run it on the terminal. 

## Resources used
To do this I had help from Wiebe and Rico. +1

## Any thoughts?
Why do we do the things we do?

**Comment by rijkvanzanten** [comment]
> Why do we do the things we do?

Is this a question specifically for back-end tech or life in general?

* You're mixing dutch and english in your repo (`documentatie` vs `assets`)
* `.DS_Store` made it in the repo
* Your `ReadMe` file uses a different capitalization system than your other files
* You have both a `sass` and `css` folder. Is `css` the output of the `sass` folder? If that's the case, I wouldn't add it to the repo
* Keep in mind what the difference is between front-end and back-end code in your project. Right now, you have your back-end `index.js` file right next to the front-end index.html file. This will most definitely cause confusion later on. You could consider putting all the front-end stuff in a `client` folder.
