### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by CountNick** [cmda-bt/be-course-18-19#92]
# Package

## Name
Nick Meijer

## Class
TECH3

## Repo link
[Project Tech Repository](https://github.com/CountNick/Project-Tech)

## Summary
* Made a npm project through npm init
* Installed the camelcase package via npm
* Imported and used the camelcase package in my js program
* Installed nodemon via npm
* Made a .gitignore file for the first time
* commited, pushed, and pulled my work through the CLI for the first time

## Resources used
* The slides
* [.gitignore](https://help.github.com/en/articles/ignoring-files)
* [package.json](https://docs.npmjs.com/files/package.json)
* [license](https://help.github.com/en/articles/licensing-a-repository)

## Any thoughts?
I had some difficulties committing, and pushing my files in  through the command line for the first time, but in the end it worked out. I tried going through the learnounode guide, nut after step four i didn't really grasp it anymore. Overal the exercises went well, and i had fun doing them! 👍

**Comment by rijkvanzanten** [comment]
Good job 👍 

* I think it's safe to assume that people who are browsing GitHub / interested in working on your project now how to use Git and GitHub. IMO you can remove step 1 through 5 in your installation guide.
* Try to pick a file-naming strategy and sticking to it. Right now you have a combination of all case `README.md`, all lowercase `index.html`, PascalCase `FlowChart.png` and whatever this is called `Wiki_img`

**Comment by CountNick** [comment]
Thanks for the feedback! I'll look into it.
