### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by ccdejene** [cmda-bt/be-course-18-19#94]
# Package

## Name
`Eyob Westerink`

## Class
TECH 3

## Repo link
https://github.com/EyobDejene/projectTech

## Summary

Installed: 
* npm 
* nodemon
* express 
* express-generator
* mongoDB
----------------------------------
* Created a boilerplate
* Added a ReadMe / Licence / GitIgnore
* Added static html and css 
* Up and running server with routes.

## Resources used
* [npm](https://www.npmjs.com/)
* [nodemon](https://nodemon.io)
* [express](https://expressjs.com/)
* [mongoDB](https://docs.mongodb.com/manual/installation/)

## Any thoughts?
Not yet  🤔

**Comment by rijkvanzanten** [comment]
> Not jet 🤔

~jet~ yet 😉 

Why did you opt to make the start script an executable in the bin folder?

**Comment by EyobDejene** [comment]
When i installed express-generator it created automatically the bin directory  with the www file.
The bin/ directory serves as a location where you can define your various startup scripts. The www is an example to start the express app as a web server.

You could have different scripts like test, stop, or restart, etc. Having this structure allows you to have different startup configurations without putting everything into app.js

**Comment by EyobDejene** [comment]
> > Not jet 🤔
> 
> ~jet~ yet 😉
> 
> Why did you opt to make the start script an executable in the bin folder?
When i installed express-generator it created automatically the bin directory with the www file.
The bin/ directory serves as a location where you can define your various startup scripts. The www is an example to start the express app as a web server.

You could have different scripts like test, stop, or restart, etc. Having this structure allows you to have different startup configurations without putting everything into app.js

**Comment by ccdejene** [comment]
> Why did you opt to make the start script an executable in the bin folder?

When i installed express-generator it created automatically the bin directory with the www file.
The bin/ directory serves as a location where you can define your various startup scripts. The www is an example to start the express app as a web server.

You could have different scripts like test, stop, or restart, etc. Having this structure allows you to have different startup configurations without putting everything into app.js
