### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by LarsBreuren** [cmda-bt/be-course-18-19#95]
# Package

## Name
Lars Breuren

## Class
Tech4

## Repo link
https://github.com/LarsBreuren/BlokTech/tree/master/0.2

## Summary
Used some usefull packages and run a index.js file by a script in the package .json

## Resources used
stackoverflow, and presentations from the class.

## Any thoughts?
404

**Comment by rijkvanzanten** [comment]
I would highly recommend using a separate repo for this project. Having different folders in a master repo with version numbers for folder names is misusing git and repos..

If you really have to keep everything in the same repo for some reason, consider using different branches for the different projects.

* You forgot a `,` on line 7 of the package.json file. This won't run: https://github.com/LarsBreuren/BlokTech/blob/master/0.2/package.json#L7
* Try completing the boilerplate repo. There's no readme, no license, no clear folder structure between back-end and front-end, no .gitignore, etc
