### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by jor-s** [cmda-bt/be-course-18-19#96]
# My Introduction

## Name
Jordy Sahit

## Class
214/Tech-4

## About me
I am excited to learn deepen my knowledge about Javascript!

## Goals
Getting a better understanding of coding.

## Skill level
Beginner

## GitHub username
https://github.com/sahitj001

## GitHub repository
https://github.com/sahitj001/backend

**Comment by dandevri** [comment]
👋 Hi Jordy, the link is added to the admin sheet.
