### ISSUE TITLE
Package (Feature)

### ISSUE THREAD

**Issue by jor-s** [cmda-bt/be-course-18-19#97]
# Package

## Name
Jordy Sahit

## Class
214/Tech-4

## Repo link
https://github.com/sahitj001/backend

## Summary
I set up my backend repository. I did that by adding a license, gitignore, editorconfigfile, package.json, index.js and a readme.

## Resources used
I used **a lot** of Google and the information of the backend git.

## Any thoughts?
I found it difficult to make scripts for my index.js. I also learned more about how to install packages, for instance I realised I didn't install nodemon locally but globally so I had to make sure I did it locally.

**Comment by rijkvanzanten** [comment]
Good job!

The one nitpicky thing I found is the fact that the readme listed in your package.json is different from the one listed in your repo (ISC vs MIT)
