### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by StephanKop** [cmda-bt/be-course-18-19#98]
# My Introduction

## Name
Stephan Kop

## Class
Tech 3

## About me
I'm mainly a front-end developer. Have some experience with React-Native. 

## Goals
Would like to learn more about databases.

## Skill level
intermediate

## GitHub username
https://github.com/superstephan1

## GitHub repository
https://github.com/superstephan1/Project-Tech

**Comment by dandevri** [comment]
👋 Hi Stephan, the link is added to the admin sheet.
